### ISSUE TITLE
NVG_IMAGE_FLIPY makes image rendered in wrong position

### ISSUE THREAD

**Issue by olliwang** [memononen/nanovg#167]
When passing `NVG_IMAGE_FLIPY` as imageFlags for creating an image. The position of the image pattern is a bit weird.

For example. If I have an image with 64 width and 128 height. And if I don't pass `NVG_IMAGE_FLIPY` and want to draw it at top-left corner, the image pattern would look like this:

    nvgImagePattern(context, 0, 0, 64, 128, 0, img, 1.0f);
    nvgRect(context, 0, 0, 64, 128);

But if I passed `NVG_IMAGE_FLIPY` when creating the image, the position y specified in `nvgImagePattern()` must be shifted as the image height like this, or the image will be hidden:

    nvgImagePattern(context, 0, 128, 64, 128, 0, img, 1.0f);
    nvgRect(context, 0, 0, 64, 128);  

The situation will be more complex if you want to draw the rect other than top-left corner like (0, 100).
For non-NVG_IMAGE_FLIPY image, it's very intuitive.

    nvgImagePattern(context, 0, 100, 64, 128, 0, img, 1.0f);

But for NVG_IMAGE_FLIPY image, it will need more cares.

    nvgImagePattern(context, 0, 100 + 128, 64, 128, 0, img, 1.0f);

Finally, I was digging into the `glnvg__convertPaint()` function and found this. 

    if ((tex->flags & NVG_IMAGE_FLIPY) != 0) {
        float flipped[6];
        nvgTransformScale(flipped, 1.0f, -1.0f);
        nvgTransformMultiply(flipped, paint->xform);
        nvgTransformInverse(invxform, flipped);
    }

I'm not familiar with nvgTransform-like functions, but something like this may solve this problem?

    nvgTranslate(flipped, 0, height / 2);
    nvgTransformScale(flipped, 1.0f, -1.0f);
    nvgTransformMultiply(flipped, paint->xform);
    nvgTransformInverse(invxform, flipped);
    nvgTranslate(flipped, 0, -height / 2);

**Comment by thor-the-norseman** [comment]
Running into this issue too.

**Comment by ivalylo** [comment]
I came up with this code
```
	float m1[6], m2[6];
	nvgTransformTranslate(m1, 0.0f, frag->extent[1] * 0.5f);
	nvgTransformMultiply(m1, paint->xform);
	nvgTransformScale(m2, 1.0f, -1.0f);
	nvgTransformMultiply(m2, m1);
	nvgTransformTranslate(m1, 0.0f, -frag->extent[1] * 0.5f);
	nvgTransformMultiply(m1, m2);
	nvgTransformInverse(invxform, m1);
```
