### ISSUE TITLE
nanovg is super slow on iPad 2/iPad 3/iPhone 4s

### ISSUE THREAD

**Issue by olliwang** [memononen/nanovg#188]
Hi, is it possible to improve the performance on OpenGL ES further? I am developing an app for iOS 8 and usually I can get over 50 FPS for iPhone 6/5s without problem. But, it's pretty hard to get over 10 FPS on iPad 2/iPad 3/iPhone 4s and unfortunately all of these devices are still supported by iOS 8.

I was trying to run the Instruments with the OpenGL ES Analyzer module for iPad 2/3, and it seems the reason all pointing to the `glDrawArrays(GL_TRIANGLE_XXXXX, XX, XX)` command.

![screen shot 2014-11-20 at 23 30 12](https://cloud.githubusercontent.com/assets/76374/5127269/2430cb84-710e-11e4-8075-9f0d4a481786.png)

Here are some suggestions from the Instruments for the top four situations that happened mostly. Does this help? Thanks.

1) Dependent Texture Sampling

The fragment shader performed dependent texture reads, which are slower than non-dependent texture reads. Dependent texture reads happen when the texture coordinates are modified in the fragment shader, or when the Project or Bias variants of the texture sampling functions are called. Use dependent texture samples sparingly. If you modify texture coordinates in the fragment shader, try to move the calculations of the texture coordinates to the vertex shader so that they occur once per vertex instead of once per fragment. This can help improve performance.

![screen shot 2014-11-20 at 23 46 52](https://cloud.githubusercontent.com/assets/76374/5127523/b2b875f4-710f-11e4-9e7e-83876a3c3597.png)

2) Fragment Shader Dynamic Branching + Memory Access

Your fragment shader contains dynamic branch instructions and accesses main memory (either because of data spilling or a dependent texture sampling operation), which is an expensive combination for the GPU. To improve performance, rework the shader to eliminate one or more of these characteristics.

![screen shot 2014-11-20 at 23 47 14](https://cloud.githubusercontent.com/assets/76374/5127530/bf054e4a-710f-11e4-9933-de89954b6d14.png)

3) Loss Of Depth Test Hardware Optimizations

Depth test hardware optimizations allow the GPU to skip calculations for pixels that would be discarded by the depth test.

 Your application used the following feature: discard fragment in a fragment shader. If possible, rework your rendering pipeline to avoid using this feature. If you must draw using this feature, attempt to do so at the end of each frame while covering the fewest number of pixels possible.

![screen shot 2014-11-20 at 23 47 23](https://cloud.githubusercontent.com/assets/76374/5127536/ca385cc6-710f-11e4-9168-6285b4732fa5.png)

4) Uninitialized Texture Data

Your application made a drawing call using a texture that contains uninitialized data. If a draw call uses uninitialized data, the rendering results are incorrect and unpredictable. One way to fix this issue is to provide image data to any TexImage2D calls instead of a NULL pointer.

![screen shot 2014-11-20 at 23 47 38](https://cloud.githubusercontent.com/assets/76374/5127542/d028de3a-710f-11e4-9074-d05cc50dfb02.png)

**Comment by Codewyvern** [comment]
Is this fixed or is the performance still slow on those devices?

**Comment by olliwang** [comment]
It's still super slow on those device (2~15 FPS). In addition, it's also hard to get 60 FPS on iPhone 6+ as well (usually only around 50 FPS).

**Comment by wtholliday** [comment]
What does Xcode's built-in GPU report show? (Debug Navigator -> FPS) It should give you a good overview of performance. Nanovg might be CPU bound in your test case.

**Comment by james4k** [comment]
My naive guess is that the heavy stencil use is a big factor.

**Comment by olliwang** [comment]
@wtholliday I tested my app (UI was built entirely with nanovg) on iPhone 6 plus and the FPS was only around 20~30. The performance is dominated by GPU for sure.
![screen shot 2015-05-31 at 15 11 20](https://cloud.githubusercontent.com/assets/76374/7901034/a64e2776-07a7-11e5-8159-a741cda16037.png)

**Comment by bengarney** [comment]
In Loom we have experimented with disabling stencil and other expensive rendering features like AA in NanoVG. Most scenes render fine without them and it can be many times faster. We've also tweaked the shader a little bit. We also have initial render texture support in our latest unstable (firehose) build which can be a major speedup depending on your use case.

**Comment by memononen** [comment]
Have you experimented splitting the shader into smaller ones? On desktop one shader is way faster but maybe on mobile multiple smaller ones is better.

**Comment by wtholliday** [comment]
Poor performance on iOS is mainly due to the discard in the fragment shader. Here's a fix, but you'll need to live without NVG_STENCIL_STROKES: https://github.com/wtholliday/nanovg/commit/f1a235ae4b6382593871de858e904e200e91c59c

Also see https://github.com/memononen/nanovg/issues/214

**Comment by olliwang** [comment]
@wtholliday Thanks. Just tried to comment out the three lines you mentioned but it seems the performance wasn't improved in my case.

**Comment by ProgrammingLife** [comment]
Has this already fixed or is the performance still slow on those devices?

**Comment by olliwang** [comment]
These devices are dead now and doesn't matter anymore. The performance of newer iOS devices came with Apple A7 CPU or later are working fine.
