### ISSUE TITLE
Feature request: more robust text rendering

### ISSUE THREAD

**Issue by rantingmong** [memononen/nanovg#193]
Hi!

I'm currently using your library for my 2D game engine to render GUI elements. Compared to Skia, your library is small, fast, and simple to use. But there's one thing that's bothering me, text rendering support is kind of simple. You can only load one font at a time and I think there's no glyph substitution built in to the library.

I want to ask if you have future plans to support things like font collections, substitution and (maybe) advanced font shaping.

I'm also thinking of modifying your library to support said features if you don't have those features planned in the near future. (Hooray for OSS!)

Thanks,
Michael

**Comment by memononen** [comment]
Hi,
You can load multiple fonts (see nvgFontFace*).
What do you mean by glyph substitution?

--mikko

**Comment by fooblah18** [comment]
Glyph substitution loads another font file if the current loaded font file doesn't have the requested glyph. If I have a string of text "Hello, 你好!" it would actually load two font files to correctly render Hello, ! and 你好 correctly.

**Comment by dougbinks** [comment]
You can load as many fonts as you like, and then implement this at a higher
level.

**Comment by memononen** [comment]
I did a quick search for glyph substitution, and looks like glyph substitution is used for ligatures and such too: http://www.microsoft.com/typography/otspec/gsub.htm
There was no mention to load additional font file, though.

AFAIK, Skia does glyph substituion using harfbuzz. I've been thinking how to support it. One option would be to have an option to compile with harfbuzz, and another option would be to make it simple to render harfbuzz layouts. Text shaping is a beast on its' own.

If you have some specific use cases in mind, that'd be useful to know.

**Comment by fooblah18** [comment]
That's what I'm thinking also! Use harfbuzz to do text layout before passing it to the renderer to do final processing. Although I did not know harfbuzz has glyph substitution built-in (their documentation is almost non-existent) so I want to base how glyph substitution is done from DirectWrite instead.

DirectWrite has an interface called `IDWriteFontFallback` ([link here](http://msdn.microsoft.com/en-us/library/windows/desktop/dn280474.aspx)). You would add a unicode subrange and specify which fonts will be used and optionally a font collection that will be affected in case a codepoint is not available in the font requested when drawing.

For now I would try to do what @dougbinks said. :smile:

PS: I get really OC when CJK fonts are not rendered correctly (I'm looking at you Chrome >:T)
