### ISSUE TITLE
Wong rendering via GLES2/Angle on Windows

### ISSUE THREAD

**Issue by jaune** [memononen/nanovg#202]
Hi, something wrong...

![ss](https://cloud.githubusercontent.com/assets/505249/6370994/195deb58-bcf7-11e4-9b1a-dd3d3ef64751.jpg)

Do you have any idea?

PS: Code working properly with emscripten.

**Comment by memononen** [comment]
Looks like stencil buffer is not set up correctly. You should create render buffer with a stencil buffer.

**Comment by jaune** [comment]
My mistake, thanks.
