### ISSUE TITLE
unwanted xpos offset when drawing text

### ISSUE THREAD

**Issue by 0ax1** [memononen/nanovg#208]
For some strings the xpos is not equivalent to the expected one when bounds are calculated / text is drawn. For example I'd like to align the text left and draw at position 0,0. So I expect the pos to be 0,0.
```
float bounds[4];
nvgTextAlign(vg, NVG_ALIGN_LEFT | NVG_ALIGN_TOP);
nvgTextBounds(vg, 0, 0, "this is a test", NULL, bounds);
printf("%f", bounds[0]);
```
If for example the string "this is a test" is used the xPosition is not 0 but -0.5. Although for most strings the xPosition is 0.

**Comment by memononen** [comment]
`nvgTextBounds()` returns the bounds of the glyphs used to render the text. Some glyphs just are "outside" the logical bounds. For example big O often starts a little bit left so that it optically aligns with the rest of the row.

**Comment by 0ax1** [comment]
Ah ok, so it's not a bug but a feature. Thanks for the info!
