### ISSUE TITLE
scissor does not work correctly for nvgText

### ISSUE THREAD

**Issue by 0ax1** [memononen/nanovg#209]
When trying to scissor drawn text with nanovg like this

```
nvgScissor
nvgText
nvgResetScissor
```

and the text-rect overlaps the scissor rect, sth. like one pixel is drawn over the scissor rect. 
So there's a tiny bit that's not scissored.

**Comment by memononen** [comment]
Could you post a screenshot of this behavior?

**Comment by 0ax1** [comment]
Here:
![over](https://cloud.githubusercontent.com/assets/1750040/6639415/b2c54d50-c98f-11e4-9f76-5c8e0b7500cf.png)

It's a modifiable slider and the value of it is displayed as text on top of it.
If I move the slider up and down the effect is easily visible. The scissor rect is the same as the darker rect on the background.

**Comment by singu1arity** [comment]
Any resolution on this, experiencing same problem?

**Comment by 0ax1** [comment]
Unfortunately not. I worked around this problem, by simply redrawing the pixels.
