### ISSUE TITLE
Question: Is there a way to render to a picture?

### ISSUE THREAD

**Issue by bigfatbrowncat** [memononen/nanovg#222]
I want to render a static part of my image to a back-buffer image. Is there a feature that allows to render off-screen to a bitmap?

**Comment by memononen** [comment]
The FBO example shows you how to render to texture. Is that what you're looking for?
https://github.com/memononen/nanovg/blob/master/example/example_fbo.c

**Comment by bigfatbrowncat** [comment]
Yes, that probably is. Thank you.
