### ISSUE TITLE
Is there a way to calculate the width of a text?

### ISSUE THREAD

**Issue by andyreimann** [memononen/nanovg#224]
Hi,

first of all thank you for this piece of software :) really appreciated!
Since I'm currently starting to use it here comes the (probably) easy question:

Is there a way to calculate the width of a text rendered with nanovg to position other texts accordingly next to it?

Best

**Comment by memononen** [comment]
Yes, take a look at the paragraph section of the demo:
https://github.com/memononen/nanovg/blob/master/example/demo.c#L852
