### ISSUE TITLE
Incorrect width of " " (space) character

### ISSUE THREAD

**Issue by bigfatbrowncat** [memononen/nanovg#225]
It looks like if I measure a single white space character with <code>nvgTextBounds(..., bounds)</code>, I every time get <code>bounds[0] = -1</code> and <code>bounds[2] = 1</code>, no matter which font size is selected. That leads to different behavior if I render "Some text" by a single string and "Some" + " " + "text" word by word with spaces between.

What's the cause of this? Is this a bug?

**Comment by bengarney** [comment]
I would assume bounds would be 0/empty and advance would be non-zero?

**Comment by memononen** [comment]
There's difference between geometry of the text and how much the current text position has advanced. This is not very well represented in the API currently.

The return value of nvgText() and nvgTextBounds() is the advance, and the rectangle returned by the bounds is more representative of the bounding box of the geometry. This might be more what you're after:
```C
float x = 10, y = 10;
x += nvgText(vg, x, y, "Some", NULL);
x += nvgText(vg, x, y, " ", NULL);
x += nvgText(vg, x, y, "text", NULL);
```
or
```C
float advance = nvgTextBounds(vg, x,y,"Text", NULL);
```

**Comment by memononen** [comment]
...and the geometry bounds can be negative too. Fonts are made to make sense optically :)

**Comment by bengarney** [comment]
Further - some fonts have buggy geometry data. Space usually works fine but
you can encounter bad ascent/descent/baseline data and may have to fix the
font file.

**Comment by bigfatbrowncat** [comment]
> There's difference between geometry of the text and how much the current text position has advanced. This is not very well represented in the API currently.
Unfortunately, I'm using another library for preparing text to render, which divides the text into single-word blocks and single-space blocks. So I can't use the "advancing" strategy.

I just want that <code>nvgTextBounds</code> function return correct horizontal bounds for a space character.

Is that possible?

**Comment by bigfatbrowncat** [comment]
> Further - some fonts have buggy geometry data.

I'm using Roboto font. I think it's flawless :)

**Comment by bengarney** [comment]
Mikko will probably say this more eloquently, but returning non-zero
advance and zero bounds for space is correct. The bounds of a space
character is nothing as it has no graphical representation. Advance tells
you how many pixels to move to render the next character in the right
place. If you want to e.g. draw a box around it you can assume it's a full
height character + use advance as the width.

**Comment by memononen** [comment]
Yes, advance tells you where to draw the next character in a string, and bounds tells you the bounds of the text you have drawn (or measured). Advance should be used to move the text location and bounds is good for drawing stuff around the text, like the rows in the demo.

What is that you're actually trying to do?

Changes are that the bounds you are getting (from -1 to 1) is actually correct for a small font size.

**Comment by bigfatbrowncat** [comment]
> The bounds of a space
character is nothing as it has no graphical representation

What should bounds stand for? I thought that it is a space that text would occupy according to internal font and kerning metrics, isn't it?

As far as I know, space character does have its width in each font (just as any other one).

If the user wants to get zero for "invisible string" width, he could use some string stripping function...

Anyway, the function doesn't return zero. It returns two (1 - (-1)), And that is strange anyway.

**Comment by bigfatbrowncat** [comment]
Tell me, could I know "how much the current text position has advanced" without actually <em>rendering</em> of the text?

**Comment by bengarney** [comment]
Call bounds, use return value?

**Comment by bigfatbrowncat** [comment]
> Call bounds, use return value?
Maybe we misunderstood each other.

Let me explain. I want to measure every peace of text - without checking is that a single space character, a word or a couple of sentences. But when I measure a single space, I (surprisingly!) get 2. See? Of course, space character is invisible and if rendering function returns a <code>correct</code> width of it, I could check, if my text is just a space, render it and get the width as a result. 

But I think this check is unnatural and could be avoided somehow. Am I right?

I see 2 beautiful solutions here:
1. Change the behavior of <code>nvgTextBounds</code> that it returns actual width of each character no matter if it is visible or not.
2. Recommend another function that calculates a correct advancing length <em>without</em> rendering cause I have to measure every word and return its size to the layout library that I use <em>before</em> rendering.

Do you see my problem now?

**Comment by bengarney** [comment]
We use nvgTextBounds return value and are able to do all text layout with
no rendering and correct widths. This works for solo spaces, zero width
strings, long strings, etc.

**Comment by bigfatbrowncat** [comment]
```
nvgFontFace(nvgContext, "Roboto-Regular.ttf");
nvgFontSize(nvgContext, 17);

// Measuring a word
nvgTextBounds(nvgContext, 0, 0, "and", NULL, bounds);
double width = bounds[2] - bounds[0];    // 23.0 -- that looks reasonable

// Measuring a single letter
nvgTextBounds(nvgContext, 0, 0, "a", NULL, bounds);
double width = bounds[2] - bounds[0];    // 9.0 -- that looks reasonable too

// Measuring a couple of spacebars
nvgTextBounds(nvgContext, 0, 0, "  ", NULL, bounds);
double width = bounds[2] - bounds[0];    // 5.0 -- Depends on font size. Looks reasonable.

// Measuring a single spacebar
nvgTextBounds(nvgContext, 0, 0, " ", NULL, bounds);
double width = bounds[2] - bounds[0];    // 2.0 -- INDEPENDENT OF FONT SIZE. That is incorrect.

```

**Comment by bengarney** [comment]
double advance = nvgTextBounds(nvgContext, 0, 0, " ", NULL, bounds); //
This will be correct, ignore bounds.

**Comment by bigfatbrowncat** [comment]
Oh, thank you! That works like a charm.

I could close the bug, but I still think the behavior is incorrect. @memononen, what do you suppose?

**Comment by memononen** [comment]
minx = -1, maxx = 1, looks like valid bounds to space if you have quite small font size, like 12px.
