### ISSUE TITLE
Two framebuffers conflict with each other

### ISSUE THREAD

**Issue by bigfatbrowncat** [memononen/nanovg#234]
I'm trying to make two dynamic framebuffer brushes and draw with them, but I have problem with color rendering - colors change and blink randomly.

The exact code:
```
	// Creating framebuffer 1
	
	if (fb == NULL) fb = nvgluCreateFramebuffer(vg, 100, 100, NVG_IMAGE_REPEATX | NVG_IMAGE_REPEATY);
	if (fb == NULL) {
		printf("Could not create FBO.\n");
		return;
	}

	nvgluBindFramebuffer(fb);
	glViewport(0, 0, 100, 100);
	glClearColor(0, 0, 0, 0);
	glClear(GL_COLOR_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);
	nvgBeginFrame(vg, 100, 100, 1);

	nvgBeginPath(vg);
	nvgRoundedRect(vg, 0, 0, 50.0f, 50.0f, 10.0f);		// Round rect
	nvgFillColor(vg, nvgRGB(255, 128, 128));			// Red color
	nvgFill(vg);
	
	nvgEndFrame(vg);
	
	// Creating framebuffer 2
	
	if (fb2 == NULL) fb2 = nvgluCreateFramebuffer(vg, 100, 100, NVG_IMAGE_REPEATX | NVG_IMAGE_REPEATY);
	if (fb2 == NULL) {
		printf("Could not create FBO.\n");
		return;
	}
	nvgluBindFramebuffer(fb2);
	glViewport(0, 0, 100, 100);
	glClearColor(0, 0, 0, 0);
	glClear(GL_COLOR_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);
	nvgBeginFrame(vg, 100, 100, 1);

	nvgBeginPath(vg);
	nvgRect(vg, 0, 0, 50.0f, 50.0f);				// Rectangle
	nvgFillColor(vg, nvgRGB(128, 255, 128));		// Green color
	nvgFill(vg);
	
	nvgEndFrame(vg);
	
	// Rendering the main screen
	
	nvgluBindFramebuffer(0);

	NVGpaint fbPaint = nvgImagePattern(vg, 0, 0, 50, 50, 0, fb->image, 1.0f);
	NVGpaint fbPaint2 = nvgImagePattern(vg, 0, 0, 200, 200, 0, fb2->image, 0.5f);

	glfwGetWindowSize(window, &winWidth, &winHeight);
	glfwGetFramebufferSize(window, &fbWidth, &fbHeight);

	// Calculate pixel ration for hi-dpi devices.
	pxRatio = (float)fbWidth / (float)winWidth;

	// Update and render
	glViewport(0, 0, fbWidth, fbHeight);
	glClearColor(0.2f, 0.2f, 0.2f, 1.0f);
	glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);

	nvgBeginFrame(vg, fbWidth, fbHeight, pxRatio);
	
	nvgBeginPath(vg);
	nvgRect(vg, 0.0f, 0.0f, winWidth, winHeight);
	nvgFillPaint(vg, fbPaint);
	nvgFill(vg);

	nvgBeginPath(vg);
	nvgRect(vg, 0.0f, 0.0f, winWidth, winHeight);
	nvgFillPaint(vg, fbPaint2);
	nvgFill(vg);
	
	nvgEndFrame(vg);
```

Result:
![ss1](https://cloud.githubusercontent.com/assets/317189/8673929/3b0bd666-2a43-11e5-9a9f-1c402a2a052a.jpg)
![ss2](https://cloud.githubusercontent.com/assets/317189/8673935/46841382-2a43-11e5-9f88-4d47557d1e3b.jpg)

The correct result (as I expect it) should be <em>big green semi-transparent squares over little pink round-rect squares</em>. 
The actual result has correct shape, but colors blink and change randomly each frame between green, pink and black. Colors of both layers change independently.

What am I doing wrong?

**Comment by olliwang** [comment]
Try adding `nvgluBindFramebuffer(NULL);` after the two `nvgEndFrame(vg);` lines after you finished your framebuffers.

**Comment by bigfatbrowncat** [comment]
It's already there:
```
    ...
    nvgEndFrame(vg);

    // Rendering the main screen

    nvgluBindFramebuffer(0);

    NVGpaint fbPaint = nvgImagePattern(vg, 0, 0, 50, 50, 0, fb->image, 1.0f);
    NVGpaint fbPaint2 = nvgImagePattern(vg, 0, 0, 200, 200, 0, fb2->image, 0.5f);
    ...
```
Isn't it in the right place?

**Comment by olliwang** [comment]
Not after your first `nvgEndFrame()`. I think `nvgluBindFramebuffer(NULL);` should always be called before your calling another `nvgluCreateFramebuffer()`.

**Comment by bigfatbrowncat** [comment]
I've added the line like this:
```
	nvgEndFrame(vg);
	nvgluBindFramebuffer(0);
	
	// Creating framebuffer 2
```

The same result.

**Comment by olliwang** [comment]
Did you try replace the two `nvgImagePattern()` lines as follow? In my app, I need to set the `y` to the same value as `height` to make it works properly. I created a issue about this almost one year ago. https://github.com/memononen/nanovg/issues/167

    NVGpaint fbPaint = nvgImagePattern(vg, 0, 50, 50, 50, 0, fb->image, 1.0f);
    NVGpaint fbPaint2 = nvgImagePattern(vg, 0, 200, 200, 200, 0, fb2->image, 0.5f);

**Comment by bigfatbrowncat** [comment]
I haven't specified `NVG_IMAGE_FLIPY` flag, actually...
Anyway, I've tried this modification and it doesn't change anything at all.

**Comment by bigfatbrowncat** [comment]
Again, the shapes look fine. The only problem is with colors.

**Comment by bigfatbrowncat** [comment]
Any ideas about how to fix this?

**Comment by memononen** [comment]
Which platform you're using? If you add `glFlush()` before rendering to main screen, will it change anything?

**Comment by bigfatbrowncat** [comment]
Actually, I'm using an old Lenovo Thinkpad notebook with Windows 8.1. I initialize GL with hints for 3.1.

```
#ifdef __APPLE__
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
	
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
	glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
#else
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
	glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
#endif
```

If I run the same code on OS X (with GL hints 3.2), everything works fine. `glFlush()` doesn't help :(

I've just tried to execute the same executable on another HP notebook with Windows 7 on the board, the issue is reproduced there.

**Comment by memononen** [comment]
Have you tried to render to the FBO without nanovg? Or have you tried GL2? If the problem is jsut random colors, then I suspect the problem is the uniform buffer object use in GL3. Older intel cards indeed have worse drivers. I only have a Mac to test on, so the changes are that I might be able to help much.

**Comment by bigfatbrowncat** [comment]
As I understand, there is no special point in the code that connects color with shader. Am I right that the color is being sent inside `GLNVGfragUniforms` structure?

**Comment by bigfatbrowncat** [comment]
I'm trying to understand how could color be broken... maybe that's only a problem with the fragment shader

**Comment by memononen** [comment]
Yes, the "paint" is always either a gradient (solid color is gradient with same colors), or a texture. The params are set via uniforms. For GL3 we use uniform buffers, and update them just once per begin/end frame, and on GL2 all the uniforms are set per drawcall. I had some problems with uniform buffers at some point, so that might be the problem, try disabling them. See `NANOVG_GL_USE_UNIFORMBUFFER ` at the top of the `nanovg_gl.h`.

**Comment by bigfatbrowncat** [comment]
It's hard for me now to turn to GL2. Is it possible to switch `NANOVG_GL_USE_UNIFORMBUFFER` while using GL3?

**Comment by memononen** [comment]
Should be as easy as commenting out this line:
https://github.com/memononen/nanovg/blob/master/src/nanovg_gl.h#L43

**Comment by bigfatbrowncat** [comment]
Great! That worked like a charm.

So the result of my investigation: on Intel HD 3000 video chip under Windows we should not define `NANOVG_GL_USE_UNIFORMBUFFER` for GL3.

What have I lost by undefining this? Performance?

**Comment by memononen** [comment]
Yes, some performance. On older cards it might not be a huge loss, though.

--mikko

**Comment by bigfatbrowncat** [comment]
Thank you. I think that problem should be somehow reflected in documentation...
