### ISSUE TITLE
Cannot load CJK font

### ISSUE THREAD

**Issue by tioover** [memononen/nanovg#242]
`nvgCreateFont` load any CJK font (for example https://github.com/adobe-fonts/source-han-sans), will return `-1`.

Test in Mac OSX, replace example font as any CJK font.

**Comment by memononen** [comment]
Hi, CJK fonts should be supported. Can you try to trace the debugger to see where it fails?

**Comment by tioover** [comment]
https://github.com/memononen/nanovg/blob/master/src/fontstash.h#L903
call `fons__tt_loadFont`
https://github.com/memononen/nanovg/blob/master/src/fontstash.h#L164
look like freetype error

**Comment by tioover** [comment]
I found reason, the stb library only support ms cmap.
use freetype maybe fix.

**Comment by tioover** [comment]
Use freetype can fix it, I hope freetype become default font library.
