### ISSUE TITLE
Weird resolution bug

### ISSUE THREAD

**Issue by NicolasDe** [memononen/nanovg#247]
I have added nanovg into sdl2 and everything works great...
http://i.imgur.com/OrTd448.png

except one thing, as soon as I set non-square resolution:
http://i.imgur.com/szSZTcF.png
or
http://i.imgur.com/PVD1Uuy.png
it breaks anti aliasing or makes it really blurred.

	GLfloat ratio = (GLfloat)width / (GLfloat)height;

	glClearColor(0, 0, 0, 0);
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);

	glViewport(0, 0, width, height);
	
	nvgBeginFrame(nanovg_context, width, height, ratio);
	...

**Comment by caway** [comment]
I've just noticed the same problem.

**Comment by memononen** [comment]
Hi,

Ratio is is not aspect ratio, but how big a pixel is. For example when you
render on retina screen, you may want to use larger value.

For example in GLFW, you have "window size" and "render buffer size", and
you can use those to derive the pixel ratio:
https://github.com/memononen/nanovg/blob/master/example/example_gl2.c#L129


--mikko

**Comment by caway** [comment]
Hmm.. I've set devicePixelRatio into 1 and the problem is gone in my case.

    nvgBeginFrame( m_vg, width, height, 1 );

**Comment by NicolasDe** [comment]
Thank you a lot guys! 1.0 also fixed everything in my case.
