### ISSUE TITLE
NV_path_rendering backend

### ISSUE THREAD

**Issue by andrewcorrigan** [memononen/nanovg#25]
I would like to propose yet another backend for NanoVG based on the NV_path_rendering extension [1].  For my own code, I run primarily on NVIDIA hardware and want to take advantage of anything it has to offer, while still maintaining the portability of NanoVG.  Once I have NanoVG integrated into my code, I will give this a shot, but meanwhile, just wanted to throw this idea out there.

[1] https://developer.nvidia.com/nv-path-rendering

**Comment by werame** [comment]
> It's supported by NVidia but it the impl is bad.Fixed pipeline dependent.No vertex shader stage access.

I guess you've missed glProgramPathFragmentInputGenNV. Chromium was [perfectly happy](https://codereview.chromium.org/348843006/) with the latter. It's true that most of the Nvidia examples in their ARB NVpr txt use the fixed pipeline... because it's convenient for easy to understand examples.
