### ISSUE TITLE
error for draw a pie

### ISSUE THREAD

**Issue by coollofty** [memononen/nanovg#250]
Code piece:

    nvgMoveTo(ctx, centerx, centery);
    nvgArc(ctx, centerx, centery, radius, PI / 4, PI / 2 * 3, NVG_CW);   // from angle 45~270
    nvgLineTo(ctx, centerx, centery);

the result is a rect...but the same code for cairo is ok

**Comment by memononen** [comment]
```C
	nvgBeginPath(vg);
	nvgMoveTo(vg, centerx, centery);
	nvgArc(vg, centerx, centery, radius, NVG_PI / 4, NVG_PI / 2 * 3, NVG_CW);   // from angle 45~270
	nvgLineTo(vg, centerx, centery);
	nvgFillColor(vg, nvgRGBA(255,128,0,255));
	nvgFill(vg);
```
Looks like this for me:
<img width="115" alt="screen shot 2015-11-08 at 08 45 03" src="https://cloud.githubusercontent.com/assets/5249992/11019180/256ad16e-85f5-11e5-832b-646345edaf2a.png">
Maybe you forgot `nvgBeginPath()`?

**Comment by coollofty** [comment]
No, I called nvgBeginPath(), maybe other things problem. I'll check it out., thanks:)
