### ISSUE TITLE
Strange artifact when rendering shapes

### ISSUE THREAD

**Issue by galsasson** [memononen/nanovg#259]
Using your wonderful renderer inside openFrameworks, I get a strange artifact at the edge of shapes.

![screen shot 2016-01-07 at 8 12 29 pm](https://cloud.githubusercontent.com/assets/3430521/12187624/6b014a7c-b57b-11e5-8aaa-88fa683b0265.png)

This artifact is only visible when the shapes are moving, and is visible on the edges that are in the direction of the motion (in the screenshot the velocity of the shapes is (-1, -1)). If I pause the movement, the artifact disappears.

This is another screenshot with velocity set to (5, 5)
![screen shot 2016-01-07 at 8 21 33 pm](https://cloud.githubusercontent.com/assets/3430521/12187731/6e17cff0-b57c-11e5-8b28-c27a582ec8b5.png)

I'm able to replicate this on both Mac and Windows using GL2 and GL3.
As I said, I'm using it inside openFrameworks, which I'm aware may be the cause of this artifact, but thought you might have some insights on whats going on.

Thanks!

**Comment by memononen** [comment]
Look strange indeed. Do you clear stencil buffer each frame?

**Comment by galsasson** [comment]
Yes! I mean no, I wasn't clearing the stencil buffer. Now that I do, the artifact is gone!
Thanks you so much!
