### ISSUE TITLE
Can't get font-rendering to work at all

### ISSUE THREAD

**Issue by reFX-Mike** [memononen/nanovg#260]
For technical reasons I can't use glfw, so I had to roll my own window and context creation. After some fidgeting, I got NanoVG to work, so I can draw lines etc. now.

But no text will ever render.

I've reduced my render function to

~~~ c
nvgBeginFrame(vg, width, height, 1.f);
renderGraph(vg, 10, 10, &fps);
nvgEndFrame(vg); 
~~~

I've loaded a font etc. and in renderGraph the cursor position changes (nvgText returns a higher X coordinate than I feed in), but still I can't see any text.

I've made sure the font is loaded correctly etc. It seems to be some sort of culling is going on, but no amount of glEnable/glDisable calls has been able to fix it.

The weirdest thing is that I can't run a debug-version. It crashes during the first memset() in fonsCreateInternal(). No crashes in release...

Please help if you can.

**Comment by memononen** [comment]
Can you paste how you create the font?

**Comment by reFX-Mike** [comment]
Here is my init:

~~~
glewInit();

vg = nvgCreateGL2(NVG_ANTIALIAS | NVG_STENCIL_STROKES | NVG_DEBUG);
nvgCreateFont(vg, "sans", "z:/Roboto-Regular.ttf");
initGraph(&fps, GRAPH_RENDER_FPS, "Frame Time");
~~~

I've checked the return code of the nvgCreateFont and it's 0 (not -1 for failure).

So the font-loading seems to be fine.

I'm using the latest versions of stb_truetype.h and stb_image.h

The graph gets drawn correctly too (I can see the curve), but no text in it.

**Comment by memononen** [comment]
Weird, that should work then. Is `nvgTextBounds()` giving you sane results?

Do you have more info which kind of crash you got in the debug build?

**Comment by leranger** [comment]
Hello,
Does it relate to pull request [146](https://github.com/memononen/nanovg/pull/146) ?

**Comment by reFX-Mike** [comment]
@leranger Unfortunately it does not. Even though I indeed use the Intel HD 530 (Skylake) for my testing (lowest common denominator), I don't get any errors (printf works fine for my debug-output) and even changing the texture-format to RGBA or LUMINANCE etc. doesn't change it. It still doesn't draw.

**Comment by reFX-Mike** [comment]
@memononen Yes, the nvgTextBounds() returns a width of 58, and the bounds are 12, 10.99, 72, 25 (I assume left, top, right, bottom?)

The crash happens in fonsCreateInternal()

The line

~~~ c
memset(stash, 0, sizeof(FONScontext));
~~~

Makes it crash for me. But only in debug mode.

In the meantime I've got rid of that by including 

~~~ c
#include <malloc.h>
#include <memory.h>
~~~~

in nanovg.c after the other two includes (stdio.h and math.h) but before nanovg.h

The crash is not related to memset, but happens in "stbtt__new_active".

The line

~~~ c
STBTT_assert(z != NULL);
~~~

triggers an assertion. The pointer z is indeed NULL. It seems the "stbtt__hheap_alloc" directly before it fails.

So I now have to assume that in release-mode it returns NULL pointers and then happily writes into it?

BTW, this a 64-bit build. Does that make a difference?

**Comment by reFX-Mike** [comment]
Mystery solved. I've made the "mistake" of using the latest "stb_truetype.h" from 

https://github.com/nothings/stb

In my desperation I've replaced it with the two year old one from this git (0.8 from 2014-05-25), and now it works just fine.

**Comment by cforfang** [comment]
I see the same thing in both Win32 and x64 debug builds in MSVC2015 when updating stb_truetype.h. In release builds it runs but there's no text.

**Comment by cforfang** [comment]
The problem is that FONS_SCRATCH_BUF_SIZE is too small, causing fons__tmpalloc() to return NULL.

**Comment by reFX-Mike** [comment]
Thanks! That fixed it. I've made it 64000 instead of 16000 and it works now. What a relief. I though I was going crazy.

**Comment by reFX-Mike** [comment]
So, should I try to do a pull request and fix this stuff? I'm new to git, so I'm not sure how it all works, but I'm willing to give it a try.

**Comment by memononen** [comment]
@reFX-Mike A PR would be nice, update stb_truetype and bump the number. Github has good tutorials how to make PRs, quick googling will find them.

**Comment by reFX-Mike** [comment]
OK. I've create the PR. Please merge ASAP. I see that there are a lot of other PRs that seem to be finished, and either fix stuff or add new features. Any particular reason you haven't reviewed and accepted them?

**Comment by memononen** [comment]
I'm building a house. It unfortunately sucks up all my free time (and more).

**Comment by reFX-Mike** [comment]
What a coincidence. We just finished ours December 2014. It sucked up all our time for 18 months. Any idea when you will be finished?

BTW, found another problem. In DEBUG mode, I can't see some strokes...

**Comment by memononen** [comment]
Things should get better towards the summer. Status report, there be kitchen: https://www.instagram.com/p/BA4jyP9m6D5

If you can reproduce the missing strokes some how and open a new issue about that, that'd be great.

**Comment by reFX-Mike** [comment]
I noticed that you've merged another PR. Can you merge mine too, please?

**Comment by padiakalpesh** [comment]
I am having this exact issue in the latest version when running the examples on VS2015 (win32 debug configuration; no issues with win32 release, and x64 debug and release configurations). stbtt__hheap_alloc() tries to allocate 56004 bytes when stash->nscratch is 12544. This results in a total alloc for 68560 which is greater than 64000. Changing the size to anything above (and including) 68560 works.

I have successfully run the examples on OS X 10.11 (both x86 and x64) though.
