### ISSUE TITLE
AA on axis aligned 1px width strokes incorrect

### ISSUE THREAD

**Issue by jonbro** [memononen/nanovg#282]
![screen shot 2016-05-04 at 11 22 54 am](https://cloud.githubusercontent.com/assets/1597/15024706/d8741dca-11ea-11e6-9d97-3d36c15a3e43.png)

nvgStroke on a perfectly vertical (or horizontal) line creates a 2px stroke when width is set to 1.

The line on the right side of the screen shot is the expected behavior, created with nvgFill on a 1px wide rect.

repro code:
```
vg = nvgCreateGL3(NVG_ANTIALIAS | NVG_STENCIL_STROKES);
nvgBeginFrame(vg, winWidth, winHeight, 1);
// incorrect rendering
nvgStrokeWidth(vg, 1);
nvgBeginPath(vg);
nvgRect(vg, 55, 35, 50, 50);
nvgMoveTo(vg, 100, 200);
nvgLineTo(vg, 100, 300);
nvgStroke(vg);
// correct rendering
nvgBeginPath(vg);
nvgFillColor(vg, nvgRGBA(0, 0, 0, 255));
nvgRect(vg, 300, 100, 1, 100);
nvgFill(vg);
```

**Comment by memononen** [comment]
If you want to draw crisp lines, you need to draw them at half pixels. At first it sucks, but if you think about it, it makes total sense. A stoke is rendered as line expanded both directions by half width. 

So try this instead:
```C
nvgMoveTo(vg, 100.5f, 200);
nvgLineTo(vg, 100.5f, 300);
```

**Comment by jonbro** [comment]
thanks so much! going to close this issue.
