### ISSUE TITLE
NanoVG changes states, disrupts rendering

### ISSUE THREAD

**Issue by SubiyaCryolite** [memononen/nanovg#285]
Hello.

I want to replace my current HUD with NanoVG. However, whenever I render directly (nvgBeginFrame) or with a nanovgFrameBuffer the rest of my scene does not display. 

It seems to be an issue with state. if I make a single NanoVG call just once (after a 3 second delay for example) my scene remains blank indefinitely. Im now trying to determine what exactly nvgBeginFrame does to my environment. 

Regardless of where I place the NanoVG code in my display function the rest of the scene simply doesn’t render at all. All I get is a white screen with the NanoVG elements. If I get rid of NanoVG calls within the begin/end frame functions my scene renders just fine. I've taken a look at the glnvg__renderFlush function and cant figure out which of the calls is causing this problem.

Furthermore I haven't been able to find any tutorial combining NanoVG and OpenGL render calls (i.e overlaying a 3D mesh). So its hard for me to determine what I’m doing wrong. Below is an example of my NanoVG call.

nvgBeginFrame(je.vg, je.gameWidth(), je.gameHeight(), 1.0f);
nvgSave(je.vg);

colorA.r(1).g(0).b(0).a(1);
nvgBeginPath(je.vg);
nvgRect(je.vg, 0, 0, 340, 30);
nvgFillColor(je.vg, colorA);
nvgFill(je.vg);

nvgRestore(je.vg);
nvgEndFrame(je.vg);

This is my current HUD. http://media.indiedb.com/images/downloads/1/82/81436/scndgen_legacy_2015-1-28-57903-s.png

**Comment by memononen** [comment]
The readme describes the state that is changed by nanovg. Are you restoring those after nanovg has rendered?

**Comment by SubiyaCryolite** [comment]
Hi. I've only restored glEnable(GL_BLEND); as that's the only flag I explicitly set at startup. Im not sure what the "defaults" are for the other states because I don't modify them.

**Comment by memononen** [comment]
nanovg tries to restore to some sane values. but for example textures and shaders are set to something else. the opengl reference manual has defaults for each state.

**Comment by SubiyaCryolite** [comment]
Thanks. Ill take a look into that.

**Comment by SubiyaCryolite** [comment]
Just in case anyone stumbles upon this in the future. A lot of initial values for various parameters are listed here.

https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGet.xml

**Comment by SubiyaCryolite** [comment]
Hi memononen, I figured out the problem

#if NANOVG_GL_USE_UNIFORMBUFFER
enum GLNVGuniformBindings {
	GLNVG_FRAG_BINDING = 0,
};
#endif

and

glUniformBlockBinding(... , GLNVG_FRAG_BINDING);

Im using GL4.4 and the block binding messed up my shaders persistent mappings (which were bound to block zero). I think it will be helpful to explicitly state that users should reserve block 0 going forward.

Thanks a lot for your help
