### ISSUE TITLE
SVG backend for nanovg

### ISSUE THREAD

**Issue by wtholliday** [memononen/nanovg#290]
I'd like to generate SVGs from my app's UI. How hard would it be to write an SVG backend for nanovg?

**Comment by memononen** [comment]
The backends are currently receiving something like tesselated triangles. So the SVG stuff should happen much earlier. I think currently it might be easier to do a wrapper to nanovg and do the backend stuff at that level.

**Comment by wtholliday** [comment]
@memononen ok thanks for the advice! I'll close this out.
