### ISSUE TITLE
Trying to draw an arc

### ISSUE THREAD

**Issue by JochenJankowai** [memononen/nanovg#296]
Hej!
First of all, thanks for this great tool, it has helped us alot!
I am trying to draw an arc and I believe that the path I am drawing is correct, at least the stroke looks like it (see below). Only when I try to fill it, it fills a rectangle around the whole thing.
I have seen a similar issue posted here before but unfortunately it wasn't resolved ([#271](https://github.com/memononen/nanovg/issues/271)). I'm guessing that there is a problem with the stencil buffer but I wouldn't know where I am going wrong.
`glEnable(GL_STENCIL_TEST);` and `glClear(GL_STENCIL_BUFFER_BIT);` are called before I draw anything and `glDisable(GL_STENCIL_TEST);` is called afterwards.
The code you see below comes from a layer I added for our framework, the functions do the exact same as their nvg... equivalents with the difference that I don't have to hand in the context every time and can use vec2s etc. The way I draw the arc is as follows:

`NanoVG::beginPath();`
`NanoVG::moveTo(origin + (arcVec1 * radii.x));`
`NanoVG::lineTo(origin + (arcVec1 * radii.y));`
`NanoVG::arc(origin, radii.y, angles.x, angles.y, NVG_CW);`
`NanoVG::lineTo(origin + (arcVec2 * radii.x));`
`NanoVG::arc(origin, radii.x, angles.y, angles.x, NVG_CCW);`
`NanoVG::closePath();`

`NanoVG::strokeColor(vec4(0, 0, 0, 1));`
`NanoVG::stroke();`

`NanoVG::fillColor(vec4(dis(gen), dis(gen), dis(gen), dis(gen)));`
`NanoVG::fill();`

`NanoVG::restore();`

As I said, the stroke looks fine. Am I missing anything fundamental here?

![canvas-20160803_133036](https://cloud.githubusercontent.com/assets/2997626/17364110/9f7fe86a-597e-11e6-8d4e-10de16e4cae1.png)

**Comment by memononen** [comment]
Check that you create the OpenGL context with stencil buffer.

**Comment by JochenJankowai** [comment]
The OpenGL context is created like so: `nvgCreateGL3(NVG_ANTIALIAS | NVG_STENCIL_STROKES);`
I have labelled the 4 points in the order they are connected. The strange thing is that if I draw a line between the two last points (4 and 1) instead of an arc it works perfectly fine:
![canvas-20160804_160731](https://cloud.githubusercontent.com/assets/2997626/17405000/270f0a10-5a5e-11e6-9af1-d6f3aeea5894.png)

**Comment by memononen** [comment]
That function creates the nanovg context. What do you use to create the window where you render into, how do you set up opengl itself?

There's special case for convex shapes, which is not prone to the stencil problem.

**Comment by JochenJankowai** [comment]
As far as I can see, stencil buffer is set up correctly. We use Qt with its OpenGL and the stencil flag is set.

So if it's not the stencil buffer, what is the special case based on?

**Comment by memononen** [comment]
It is definitely something wrong with the stencil buffer. If you call glGet with 
GL_STENCIL_BITS just before nvgBeginFrame() what so you get?

**Comment by JochenJankowai** [comment]
The number returned by 
`int status;`
`glGetIntegerv(GL_STENCIL_BITS, &status);`
`std::cout << status << std::endl;`
varies depending on what I draw but stays constant during runtime.
Right now I am getting 1394322787.

**Comment by memononen** [comment]
Does not look right. I would expect 8, or 0 if there's no stencil buffer. Can you show how you initialize the opengl with qt? Are you using stencil for something else?

**Comment by lathen** [comment]
I noticed this issue and have had the same problems (I believe Jochen is dealing with https://github.com/inviwo/inviwo as I have been..). The problem was with the setup of the framebuffer object. I initially took inspiration from 
https://github.com/memononen/nanovg/blob/master/src/nanovg_gl_utils.h#L80-L91 which shows an example on how to set this up. The key was to use a render buffer object for the stencil buffer as shown in the example. What I ended up with was:

```
RenderBufferObject stencilBuffer;
stencilBuffer.activate();
glRenderbufferStorageEXT(GL_RENDERBUFFER_EXT, GL_DEPTH24_STENCIL8_EXT, screenDim.x, screenDim.y);
glFramebufferRenderbufferEXT(GL_FRAMEBUFFER_EXT, GL_DEPTH_ATTACHMENT_EXT, GL_RENDERBUFFER_EXT, stencilBuffer.getID());
glFramebufferRenderbufferEXT(GL_FRAMEBUFFER_EXT, GL_STENCIL_ATTACHMENT_EXT, GL_RENDERBUFFER_EXT, stencilBuffer.getID());
```

Sorry for mixing in some Inviwo-specifics here (e.g. the RenderBufferObject), but I hope the idea is clear.. Note that I had to use the EXT versions for some reason, and that it only worked with the GL_DEPTH24_STENCIL8_EXT storage type. This might be due to how the OpenGL context was initially setup by Qt, but I'm in over my head here..

**Comment by memononen** [comment]
Thanks for chiming in. That explains why the `GL_STENCIL_BITS` returned bogus values. I think there's new API which deals with frame/render buffers [1].

[1] http://stackoverflow.com/questions/27371067/how-to-query-the-depth-of-the-opengl-stencil-buffer

**Comment by JochenJankowai** [comment]
Sorry for the late reply. @lathen 's hint solved the problem eventually.
Thanks for your help!
