### ISSUE TITLE
Used NanoVG on this projection project

### ISSUE THREAD

**Issue by lab101** [memononen/nanovg#309]
Hey,

This isn't an issue but just a big thx for this nice library. 
Looking at these smooth lines instead of the standard OpenGL lines makes me really happy. Using it on almost all my new projects.
Did use it recently on this project:
[http://www.lab101.be/projects/capitalm.html](http://www.lab101.be/projects/capitalm.html)

Greets
Kris

**Comment by Nasso** [comment]
The link is a 404 when clicking on it ! But works when copy-pasted/select-dragged-on-a-new-tab

**Comment by lab101** [comment]
Ah your right made a mistake in markdown

**Comment by Nasso** [comment]
It works now ! Good job too !
