### ISSUE TITLE
Incorrect coordinates when drawing to an FBO

### ISSUE THREAD

**Issue by xeekworx** [memononen/nanovg#314]
I'm creating an FBO using nvgluCreateFramebuffer, then binding to it, and finally setting my glViewport to the width and height of that FBO, glViewport(0, 0, 300, 300); Unfortunately, when I draw, the coordinates don't seem to make much sense. If I use nvgRect(s_context, 0, 0, 150, 150), the rectanngle isn't visible when I render that FBO's texture back to the screen. I know it's actually drawing a rectangle because if I do something like nvgRect(s_context, 150, 150, 150, 150); I can then see it. What's going on with nanovg's coordinates? I don't have this issue if I render to the default frame buffer.

**Comment by memononen** [comment]
Are you following all the setup steps from the example?
https://github.com/memononen/nanovg/blob/master/example/example_fbo.c#L33

**Comment by xeekworx** [comment]
Not exactly. I don't handle pixel ratio stuff and I'm not trying to make a pattern of sorts. It's just an off screen buffer I want. At the moment I'm just trying to draw a 150x150 pixel square within it and then the FBO's image back to the screen. I don't see it at all in the FBO at 0,0, but when I draw it at 50,150 it's not even the right shape.

Here's my FBO drawing:

```
	NVGcontext * vg = NULL;
	if(NULL == (vg = nvgCreateGL3(NVG_ANTIALIAS | NVG_STENCIL_STROKES))) {
		std::cout << "Failed to create NVG Context" << std::endl;
		SDL_GL_DeleteContext(glcontext);
		SDL_DestroyWindow(main_window);
		SDL_Quit();
		return 1;
	}

	NVGLUframebuffer * fbo = NULL;
	if(NULL == (fbo = nvgluCreateFramebuffer(vg, FBO_WIDTH, FBO_HEIGHT, 0))) {
		std::cout << "Failed to create NVG Frame Buffer" << std::endl;
		nvgDeleteGL3(vg);
		SDL_GL_DeleteContext(glcontext);
		SDL_DestroyWindow(main_window);
		SDL_Quit();
		return 1;
	}

	nvgluBindFramebuffer(fbo);
	glViewport(0, 0, FBO_WIDTH, FBO_HEIGHT);
	glClearColor(1.0f, 1.0f, 1.0f, 1.0f);
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);
	nvgBeginFrame(vg, FBO_WIDTH, FBO_HEIGHT, 1.0f);
	nvgBeginPath(vg);
	nvgRect(vg, 50, 150, 150, 150);
	nvgFillColor(vg, nvgRGBA(0, 0, 255, 255));
	nvgFill(vg);
	nvgEndFrame(vg);

	nvgluBindFramebuffer(NULL);
	glViewport(0, 0, WINDOW_WIDTH, WINDOW_HEIGHT);
```

Then here is where I render the FBO to the screen:

```
		glClearColor(0.0f, 1.0f, 0.5f, 0.0f);
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);

		nvgBeginFrame(vg, WINDOW_WIDTH, WINDOW_HEIGHT, 1.0f);
		NVGpaint paint_img = nvgImagePattern(vg, 0, 0, FBO_WIDTH, FBO_HEIGHT, 0.0f, fbo->image, 1.0f);
		nvgSave(vg);
		nvgBeginPath(vg);
		nvgRect(vg, 0, 0, FBO_WIDTH, FBO_HEIGHT);
		nvgFillPaint(vg, paint_img);
		nvgFill(vg);
		nvgRestore(vg);
		nvgEndFrame(vg);

		SDL_GL_SwapWindow(main_window);
```

Here's the result:

[http://i.imgur.com/3VJdALB.png](http://i.imgur.com/3VJdALB.png)

**Comment by xeekworx** [comment]
Odd. I wouldn't have expected this. I set the x,y parameters of nvgRect to 0,0 and moved those values to a nvgTranslate call above it and now I'm seeing what is actually expected. I'm not really sure why I have to do this for FBOs.

```
		glClearColor(0.0f, 1.0f, 0.5f, 0.0f);
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);

		nvgBeginFrame(vg, WINDOW_WIDTH, WINDOW_HEIGHT, 1.0f);
		NVGpaint paint_img = nvgImagePattern(vg, 0, 0, FBO_WIDTH, FBO_HEIGHT, 0.0f, fbo->image, 1.0f);
		nvgSave(vg);
		nvgBeginPath(vg);
		nvgTranslate(vg, 50.0f, 50.0f); // ADDED TRANSLATE
		nvgRect(vg, 0, 0, FBO_WIDTH, FBO_HEIGHT); // SET X,Y to 0,0 from 50.0, 50.0
		nvgFillPaint(vg, paint_img);
		nvgFill(vg);
		nvgRestore(vg);
		nvgEndFrame(vg);

		SDL_GL_SwapWindow(main_window);
```

**Comment by xeekworx** [comment]
This also means NVG_IMAGE_REPEATX | NVG_IMAGE_REPEATY has to be the flags for my FBO else it still has strange coordinates even with the translate.

**Comment by memononen** [comment]
Ping @olliwang , did you have issues with FBO rendering at some point?

**Comment by olliwang** [comment]
@memononen Yes, when it comes to FBO, I need to specify coordinate like this `nvgImagePattern(0, height, width, height, 0, fbo->image, 1)` to make it work. I thought maybe it's caused by the `NVG_IMAGE_FLIPY` parameter passed to `nvgCreateImageRGBA()` in `nvgluCreateFramebuffer()`. 

BTW, this issue does not exist in the `bgfx` backend when I added NanoVG FBO support for `bgfx`. I was checking the implementation of `bgfx` to find out why, and realized that the backend does not respect `NVG_IMAGE_FLIPY` at all. Maybe that's the reason.

**Comment by memononen** [comment]
@olliwang I remember fixing that issue :/ But I guess it got lost somewhere. I wish I had the time to pick that up. We got one of those small things that is on your profile pic just a week ago :) So now, I have no time and I'm really tired.

I think the last snippet by @ivalylo on #167 is correct. Needs some testing, though. Could I ask you test it and make a PR if it works correctly?

**Comment by xeekworx** [comment]
**The pattern parameters @olliwang speaks of aren't quite what it takes to get things right.** It does indeed work if the rect's origin ends up being at the coordinate 0, 0. If I want to draw my rect with the FBO's texture as a pattern at let's say, 50, 50 then nvgImagePattern has to have these parameters:

```
float x = 50, y = 50;
NVGpaint paint = nvgImagePattern(vg, x, source_height + y, source_width, source_height, 0.0f, fbo->image, 1.0f);

nvgRect(vg, x, y, source_width, source_height);
nvgFillPaint(vg, paint);
nvgFill(vg);
```
Notice I also had to change _ox_, but then also add the target y to the source's height for the _oy_ parameter.

The pattern origin seems to be the screen's origin rather than the target rect's origin. This wasn't what I expected. It's not how I remember any other APIs working, but maybe this is normal I don't know for sure. Maybe just doing it this way will have my issue resolved, unless @memononen this isn't how you actually intended image pattern coordinates to work.

I still feel something isn't quite right about it.

**Comment by memononen** [comment]
Textures and frame buffers have different origin on OpenGL, which sucks. The flip-y thing you may have seen around was supposed to fix this, but I think my test case was not sufficient to fix it. Rendering to FBO and using it should work as any other image patterns.

There's no direct correlation between pattern and shape. Patterns are defined in the same coordinate system as shapes. This is the same in html canvas too.

**Comment by olliwang** [comment]
The code mentioned in #167 should work as expected. I just tested it with my iOS app that heavily relies on FBO and the app contains more than hundreds of thousands lines of the code. The rendering result looks totally the same after applying the changes. 

@memononen Just submitted a PR, cheers!

![img_7061](https://cloud.githubusercontent.com/assets/76374/18614035/d067f9d2-7db8-11e6-8a87-f1f5cd011f8b.PNG)

**Comment by memononen** [comment]
@xeekworx I just merged @olliwang's fix for y-flipping. Can you check that everything works for you now as expected? This should work now:

```C
float x = 50, y = 50;
NVGpaint paint = nvgImagePattern(vg, x, y, source_width, source_height, 0.0f, fbo->image, 1.0f);
nvgRect(vg, x, y, source_width, source_height);
nvgFillPaint(vg, paint);
nvgFill(vg);
```

The pattern positioning in the same coordinate system as rectangle is by design.

**Comment by xeekworx** [comment]
@memononen yes this works!
