### ISSUE TITLE
Drawing circles and circle sectors

### ISSUE THREAD

**Issue by ReneTrefft** [memononen/nanovg#318]
For drawing circle sectors I use the following code:

```c++
float currentAngle;
int circlePoints = 100;
float centerX = 500.0f;
float centerY = 500.0f;
float radius = 30.0f;
int degrees = 45;

nvgBeginFrame(vg, ...);
nvgBeginPath(vg);

nvgMoveTo(vg, centerX, centerY);

for (int i = 0; i < circlePoints; ++i) {
  currentAngle = 2 * M_PI / 360 * degrees * i / circlePoints ;
  nvgLineTo(vg, centerX + cos(currentAngle)*radius, centerY + sin(currentAngle)*radius);
}

nvgFillColor(vg, nvgRGBA(255, 255, 255,255));
nvgFill(vg);

nvgClosePath(vg);
nvgEndFrame(vg, ...);
```

If `degress = 360` a completely closed circle should be drawn. But there is still a subtle line which is not drawn:

![2016-09-21 20_25_23-greenshot](https://cloud.githubusercontent.com/assets/8194552/18723631/a3c54820-8039-11e6-9b91-68426cc693d1.png)

Any idea what's going wrong here?

**Comment by mcourteaux** [comment]
Yes, that is most likely the anti aliasing that causes this 1px heigh line to be less intense. This behaviour is expected. To fix this, you should fix your own code and verify if you will draw a full circle.

**Comment by memononen** [comment]
It's because of the moveTo to the center, very sharp lines (it goes back and forth along the same line) can sometimes confuse the AA algorithm.

A better, but uglier solution is to use:
```C
for (int i = 0; i < circlePoints; ++i) {
  float px, py;
  currentAngle = 2 * M_PI / 360 * degrees * i / circlePoints ;
  px = centerX + cos(currentAngle)*radius;
  py = centerY + sin(currentAngle)*radius;
  if (i == 0)
    nvgMoveTo(vg, px, py);
  else
    nvgLineTo(vg, px, py);
}
```

**Comment by ReneTrefft** [comment]
Thx for any help! Now I use this code for drawing a part of a ring .
But if I do this

```c++
nvgBeginPath(vg);

float currentAngle, px, py;

nvgMoveTo(vg, centerX, centerY);
for (unsigned int i = 0; i < circlePoints; ++i) {
    currentAngle = float(-0.5*M_PI + 2 * M_PI * 0.5 * i / circlePoints);
    px = centerX + cos(currentAngle)*cursorRadius;
    py = centerY + sin(currentAngle)*cursorRadius;
    if (i == 0)
        nvgMoveTo(vg, px, py);
    else
        nvgLineTo(vg, px, py);
    }
}

nvgMoveTo(vg, centerX, centerY);
for (unsigned int i = 0; i < circlePoints; ++i) {
    currentAngle = float(-0.5*M_PI + 2 * M_PI * 0.5 * i / circlePoints);
    px = centerX + cos(currentAngle)*cursorRadius*0.65;
    py = centerY + sin(currentAngle)*cursorRadius*0.65;
    if (i == 0)
        nvgMoveTo(vg, px, py);
    else
        nvgLineTo(vg, px, py);
    }
    nvgPathWinding(vg, NVG_HOLE);
    nvgFillColor(vg, nvgRGBA(255, 255, 255, 255));
    nvgFill(vg);
}
```
I get a ring with a small line. 

![2016-09-22 12_28_29-greenshot](https://cloud.githubusercontent.com/assets/8194552/18744926/53316f7e-80c0-11e6-8ac5-998dcfb733af.png)

Again, any idea how to fix that?

**Comment by mcourteaux** [comment]
Again, just don't start from the center. Instead start immediately on one side (outer or inner) of the ring. If the shape you are willing to make does not go through the center, then your code shouldn't do that either.
