### ISSUE TITLE
Feature request: Allow to create a NanoVG image object from an already existing GL Texture2D.

### ISSUE THREAD

**Issue by mcourteaux** [memononen/nanovg#319]
In the application I'm building, it would be awesome to have the ability to draw GL textures created not through any of the NanoVG ways. Now, I'm hacking my way around it. I'm suggesting a function like:

    int nvgCreateImageFromGlTexture(GLuint texture, int texture_w, int texture_h, int content_w, int imageFlags);

The need for the two parameters `content_w` and `texture_w` is to allow for custom image formats (by which I mean non-RGBA). This is needed because the hardware requires image data row lengths to be a multiple of 4 bytes. Using RGBA 8-bit, this is always fulfilled. However, I'd be using a couple of formats, like RGB 8-bit and RGB 16-bit. These formats have a pixel size of 3 and 6 bytes per pixel, respectively. So, there is the need for extra padding when the image width times the pixel size is not a multiple of 4 bytes. For more information about this: https://www.opengl.org/wiki/Common_Mistakes#Texture_upload_and_pixel_reads

However, this would require `struct GLNVGtexture` to have one more field: `contentWidth` in order to be able to correct for the padding in when calculating the transform in `nvgImagePattern()`.

**Comment by memononen** [comment]
That functionality exist already:
https://github.com/memononen/nanovg/blob/master/src/nanovg_gl.h#L62

They are per GL implementation in order to allow to build one binary which has all the GL backends compiled and choose at runtime which one to use.

**Comment by mcourteaux** [comment]
Okay, I will experiment with this soon (as I'm doing some major design changes and the build is broken at the moment). Thank you! If I understand correctly, I could compensate for the padding myself by just increasing the `width` parameter to `nvgImagePattern()`?

**Comment by memononen** [comment]
The image is defined as pattern. It has origin and size (and rotation). When you draw a shape using the image pattern, only the pixels will be drawn which are visible "through" the shape.

NanoVG assumes RGBA premultipled alpha images. If your textures are in funky format, one option is to first draw them into an RGBA8 FBO using your own pixel shader and then use them as image pattern.
