### ISSUE TITLE
Problem with composite paths

### ISSUE THREAD

**Issue by Rado-1** [memononen/nanovg#322]
I'm currently integrating NanoVG to[ ZGameEditor](http://www.zgameeditor.org/) as an external library (Windows DLL and Android .so) and everything works fine, except of one problem - composite paths do not work. For example, the following code:
```
nvg_BeginPath();
nvg_Rect(0, 0, 2, 2);
nvg_Circle(2, 2, 1);
nvg_FillColor(0.8, 0.1, 0.1, 1.0);
nvg_Fill();

nvg_BeginPath();
nvg_Rect(0, 0, 2, 2);
nvg_StrokeWidth(0.05);
nvg_StrokeColor(0.1, 0.8, 0.1, 1.0);
nvg_Stroke();

nvg_BeginPath();
nvg_Circle(2, 2, 1);
nvg_Stroke();
```
(note I'm using `nvg_` prefix instead of `nvg`, colors are specified as <0-1> 4 floats, and positions are scaled) results in this:
![screenshot](https://dl.dropboxusercontent.com/u/25552453/scr1.jpg)
Independently on usage or omitting `nvg_PathWinding()` the result of composing paths is always the same: bounding box comprising all the included paths.

When I compile your C++ examples, path composition works fine, but when I try to call it from ZGameEditor the problem occurs. It maybe/probably uses some settings or handling of OpenGL which is not compatible to NanaoVG's expectations.

I can provide you my example(s), binaries, VS projects for building the library, etc. to reproduce the problem. But before that, you maybe already know or suspect what's the problem and how to solve it. Thanks for your help!

**Comment by notlion** [comment]
Looks to me like you may need to enable stencil buffer on your OpenGL context and/or framebuffer.

**Comment by Rado-1** [comment]
Thanks Ryan. You are right. ZGameEditor did not use stencil buffer in created OpenGL context. I discussed this with the author of the tool and this feature will be added soon. After it's done,  NanoVG will be used as an extension of another game engine.
