### ISSUE TITLE
Font rendering of umlauts

### ISSUE THREAD

**Issue by ReneTrefft** [memononen/nanovg#326]
An umlaut (ÄÖÜäöü) aborts the rendering process. The umlaut itself and any chars after the umlaut are not appearing. Tested with the Fonts Roboto Regular and Arial. Compiled with VS 2015 (Release configuration, Platform x64) on Win10 x64.

**Comment by memononen** [comment]
Are you passing the string as UTF-8? We Finns use umlauts too, and I'm pretty sure I tested it.

**Comment by ReneTrefft** [comment]
No, string was passed in ANSI. Encoding them to UTF8 first fixed the issue. Thx for help!
