### ISSUE TITLE
Need example for nvgGlobalCompositeOperation

### ISSUE THREAD

**Issue by satoren** [memononen/nanovg#339]
nvgGlobalCompositeOperation not used at examples. I didn't know how to use it.

**Comment by AndrewBelt** [comment]
I can't get this to work either. I'm just calling `nvgGlobalCompositeOperation(vg, NVG_LIGHTER);` before an `nvgFill(vg);` call and the result is unaffected.

**Comment by satoren** [comment]
Yes.It only affects the ``nvgEndFrame`` timing. It is need ``nvgEndFrame`` per change. Or apply [this](https://github.com/memononen/nanovg/pull/312/files) patch.

e.g.
```C
nvgBeginFrame(vg,100,100,1);

//Fill red
nvgFillColor(vg, nvgRGB(255,0,0));
nvgRect(vg,0,0,100,100);
nvgBeginPath(vg);
nvgFill(vg);

//Fill blue with lighter.  Expected purple
nvgGlobalCompositeOperation(vg, NVG_LIGHTER);
nvgFillColor(vg, nvgRGB(0,0,255));
nvgBeginPath(vg);
nvgRect(vg,0,0,100,100);
nvgFill(vg);

nvgGlobalCompositeOperation(vg, NVG_SOURCE_OVER);//Restore to default.
nvgEndFrame(vg);// Blue filled
```
