### ISSUE TITLE
Trying to use GLES2 backend

### ISSUE THREAD

**Issue by AndreyArsov** [memononen/nanovg#344]
I am trying to use nanovg with GLES2 backend, but when I render bezier curves things don't work.

For example the main sample gives the following when rendering the color wheel:
![image](https://cloud.githubusercontent.com/assets/9951845/21031753/fc4e7266-bd59-11e6-8088-31c4a16ab626.png)

Has anyone tried something like that? Any help is appreciated. It is possible that I have to set some GL state, but I am not sure what. I looks as if clipping is not applied in this case

**Comment by memononen** [comment]
You have to set up OpenGL so that the frame buffer you're rendering to has stencil buffer.

**Comment by AndreyArsov** [comment]
Thanks a lot, fixed.
