### ISSUE TITLE
Texture atlas and coords with nvgImagePattern

### ISSUE THREAD

**Issue by misu-rg** [memononen/nanovg#348]
Hello guys,

I'm having trouble to display a rect with a specific part of a texture atlas (no problem when displaying the full texture).

Lets say I have a 128x128 texture and want to display a rect with coords (0, 0) to (48, 48), how can I do that with nvgImagePattern ?

Thanks

**Comment by memononen** [comment]
The image pattern is described as "rectangle" in the same world space as the rectangle you're rendering. Imagine this:

```
Image
o.......................
:                      :
:      Rectangle       :
:      x------+        :
:      |      |        :
:      |      |        :
:      +------+        :
:                      :
.......................:
```

So the drawn rectangle is a "view" to the texture.

This should work pretty close to what html canvas drawImage does http://www.w3schools.com/TAgs/canvas_drawimage.asp

```
float drawImage(NVGcontext* vg, int image, float alpha,
		float sx, float sy, float sw, float sh, // sprite location on texture
		float x, float y, float w, float h) // position and size of the sprite rectangle on screen
{
	float ax, ay;
	int iw,ih;
	NVGpaint img;
	
	nvgImageSize(vg, image, &iw, &ih);

	// Aspect ration of pixel in x an y dimensions. This allows us to scale
	// the sprite to fill the whole rectangle.
	ax = w / sw;
	ay = h / sh;

	img = nvgImagePattern(vg, x - sx*ax, y - sy*ay, (float)iw*ax, (float)ih*ay,
				0, image, alpha);
	nvgBeginPath(vg);
	nvgRect(vg, x,y, w,h);
	nvgFillPaint(vg, img);
	nvgFill(vg);
}
```

**Comment by misu-rg** [comment]
Wow, thank you very much for this answer.  It's perfect !
