### ISSUE TITLE
nvgRotate axis

### ISSUE THREAD

**Issue by Wodehouse211** [memononen/nanovg#349]
Hi,

I am using nvgRotate in my application to rotate a particular widget. I have found that if I have two widgets X and Y ( Y is lying to the right of X ), and I use nvgRotate for X, Y also gets rotated. Is there any way to limit the rotation only upto a point where widget X ends?

**Comment by memononen** [comment]
This question about html canvas (the is similar) explains how to do it:
http://stackoverflow.com/questions/4649836/using-html5-canvas-rotate-image-about-arbitrary-point

**Comment by Wodehouse211** [comment]
Yes, nvgSave and nvgRestore was missing in my code. Thanks a ton! :)
