### ISSUE TITLE
Horizontal/Vertical Image Mirroring

### ISSUE THREAD

**Issue by sponge** [memononen/nanovg#351]
Is there a trick that I'm missing to mirror the contents of an NVGpaint horizontally or vertically when drawing it? I'm using nvgImagePattern to draw tiles out of one large texture atlas, but am not having much luck being able to mirror it. Scaling both through NVGScale(nvg, -1) and trying to scale the paint's x transform matrix by -1 have not seemed to work, but it might just be me being bad at matrix math. I see NVG_IMAGE_FLIPY but that's at image load, and I'd like to be able to toggle it on a per-NVGpaint basis.

**Comment by memononen** [comment]
Negative scaling should do the trick. Can you post a snippet of code which you're trying to use for that?

**Comment by sponge** [comment]
Loading the image:
```
    hnd = nvgCreateImageMem(info->nvg, 0, (unsigned char *) buffer, sz);
```

Rendering:
```
	nvgScale(nvg, -1, 1);
	auto paint = nvgImagePattern(nvg, 400, 400, 320, 32, 0, hnd, 1.0f);
	nvgBeginPath(nvg);
	nvgRect(nvg, 400, 400, 320, 32);
	nvgFillPaint(nvg, paint);
	nvgFill(nvg);
```

No visible output when nvgScale is used that way. No change if I move nvgScale to after the paint and before the path. No change if I use 400+320 to shift it by the width.

If I try `nvgTransformScale(paint.xform, -1, 1);` I get what looks like one column of fragments stretched out. Thinking it might be a tex coord thing, I tried adding `NVG_IMAGE_REPEATX` when loading the image, which gives me something different but nothing that resembles horizontal mirroring.

In this case there's no nvgTransform here, but in the real thing I'm using nvgTransform as a 2D camera control, so I'm keen on trying to adjust the paint instead of trying to change the global transform, which is why I started digging around in the NVGpaint struct and tried changing xform there.

I'm running the GL3 implementation with the HEAD revision of NanoVG

**Comment by memononen** [comment]
If you put scale there, then your rectangle will be drawn at -400,400, which is probably not what you want. Something like this should work:
```C
float x = 400, y = 400, w = 320, h = 20;
nvgSave(nvg);
nvgTranslate(nvg, x+w/2, y+h/2);  // center of the image
nvgScale(nvg, -1, 1); // flip
nvgBeginPath(nvg);
nvgRect(nvg, -w/2, -h/2, 320, 32); // center of the image at (0,0)
nvgFillPaint(nvg, paint);
nvgFill(nvg);
nvgRestore(nvg);
```

**Comment by sponge** [comment]
Yup, bitten by my not remembering how transforms work again :) Thanks!

**Comment by memononen** [comment]
If you run into problems with transforms, a good way is to google something like:
`html canvas how to flip image` and you should usually be able to derive the solution from there.
