### ISSUE TITLE
How is a good way to build examples with macOS Sierra ?

### ISSUE THREAD

**Issue by omochi** [memononen/nanovg#365]
I faced build problem and found original custom way.
Please tell me standard way.
I share my solution for others.

## Problem in my case

I tried `premake4` and `make`, but got linker error.

```
ld: library not found for -lglfw3
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## My solution

I used homebrew and pkg-config.

```
$ brew install glfw3
$ pkg-config --cflags glfw3
-I/usr/local/Cellar/glfw/3.2.1/include
$ pkg-config --libs glfw3
-L/usr/local/Cellar/glfw/3.2.1/lib -lglfw
```

I patched `premake4.lua` with these options for all executables.
7 sections are.

before

```
        configuration { "macosx" }
            links { "glfw3" }
            linkoptions { "-framework OpenGL", "-framework Cocoa", "-framework IOKit", "-framework CoreVideo", "-framework Carbon" }
```

after 

```
        configuration { "macosx" }
            buildoptions { "-I/usr/local/Cellar/glfw/3.2.1/include" }
            linkoptions { "-framework OpenGL", "-framework Cocoa", "-framework IOKit", "-framework CoreVideo", "-framework Carbon",
                "-L/usr/local/Cellar/glfw/3.2.1/lib", "-lglfw" }
```

And I could build them.

```
$ premake4 gmake
$ cd build
$ make
$ ./example_gl2
```

If it can be used pkg-config within premake4, get more easy.
But I am not familiar with premake and lua.
If someone knows anything around it, please give me information.

**Comment by memononen** [comment]
brew should add symlinks to `/usr/local/` when a library is installed, so there is something wrong with your brew setup.

**Comment by omochi** [comment]
Thank you. I looked around libraries.
My brew not installed `libglfw3.dylib` but `libglfw.dylib`, `libglfw.3.dylib`, `libglfw.3.2.dylib`

```
[omochi@omochi-MB pkgconfig]$ ls -al /usr/local/lib | grep glfw
lrwxr-xr-x    1 omochi  wheel     42  4  8 01:55 libglfw.3.2.dylib -> ../Cellar/glfw/3.2.1/lib/libglfw.3.2.dylib
lrwxr-xr-x    1 omochi  wheel     40  4  8 01:55 libglfw.3.dylib -> ../Cellar/glfw/3.2.1/lib/libglfw.3.dylib
lrwxr-xr-x    1 omochi  wheel     38  4  8 01:55 libglfw.dylib -> ../Cellar/glfw/3.2.1/lib/libglfw.dylib
```

And pkg-config also says that this Formula provide `libglfw.dylib`.
Line `Libs: -L${libdir} -lglfw` shows it.

```
[omochi@omochi-MB pkgconfig]$ cat /usr/local/Cellar/glfw/3.2.1/lib/pkgconfig/glfw3.pc
prefix=/usr/local/Cellar/glfw/3.2.1
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Name: GLFW
Description: A multi-platform library for OpenGL, window and input
Version: 3.2.1
URL: http://www.glfw.org/
Requires.private: 
Libs: -L${libdir} -lglfw
Libs.private:  -framework Cocoa -framework IOKit -framework CoreFoundation -framework CoreVideo
Cflags: -I${includedir}
```

And I found changing log of formula name in homebrew.

```
  "glfw3": "glfw",
```

https://github.com/Homebrew/homebrew-core/blob/master/formula_renames.json

So I think that the glfw3 formula provide `libglfw3.dylib` in the past,
and It was changed to glfw after a time.

Could you reinstall glfw3 via homebrew?
I guess that problem reproduce now.

```
$ brew uninstall glfw
$ brew uninstall glfw3
$ brew install glfw
```
