### ISSUE TITLE
Unable to use OTF fonts

### ISSUE THREAD

**Issue by Nairou** [memononen/nanovg#37]
You currently use stb_truetype.h for handling fonts, which can't load .otf font files. Any opposition to using freetype instead, other than adding a dependency?

**Comment by svenevs** [comment]
@memononen is it still true that `.otf` is not supported?

https://github.com/memononen/nanovg/blob/e70a78e42e781bc73393afe47a62e6c049197a0b/src/nanovg.c#L25-L26

It looks like `fontstash` is being used now, but in a parent project I'm still getting `-1` returned.  Just looking for confirmation as to whether or not `.otf` is supported.  Thanks!

**Comment by Nairou** [comment]
@svenevs It works if you enable FreeType use. Take a look at fontstash.h, you have to define FONS_USE_FREETYPE.

**Comment by svenevs** [comment]
Thanks @Nairou I completely overlooked that, adding `-DFONS_USE_FREETYPE` and using `find_package(Freetype)` works as expected.  This also greatly clarifies [the initial comment](https://github.com/memononen/nanovg/issues/37#issuecomment-35593836) desiring relative simplicity.
