### ISSUE TITLE
example crash in stb_truetype.h

### ISSUE THREAD

**Issue by wtjcn** [memononen/nanovg#377]
I run on armhf32 linux, ubuntu 14.04
In seven examples, only example_fbo can run correctly, other six examples all crash for same error:
example_gles3: ../src/stb_truetype.h:1700: stbtt__new_active: Assertion `z != ((void *)0)' failed.

>> #elif STBTT_RASTERIZER_VERSION == 2
>> static stbtt__active_edge *stbtt__new_active(stbtt__hheap *hh, stbtt__edge *e, int off_x, float start_point, void *userdata)
>> {
>>    stbtt__active_edge *z = (stbtt__active_edge *) stbtt__hheap_alloc(hh, sizeof(*z), userdata);
>>    float dxdy = (e->x1 - e->x0) / (e->y1 - e->y0);
>>    STBTT_assert(z != NULL);    ==> this line 1700

I found out, it's because example_fbo has a loadFonts function, and other six examples don't.
I copy the loadFonts function to other examples source and insert calling at :

	if (vg == NULL) {
		printf("Could not init nanovg.\n");
		return -1;
	}
	if (loadFonts(vg) == -1) {
		printf("Could not load fonts\n");
		return -1;
	}
	if (loadDemoData(vg, &data) == -1)
		return -1;
 then it fix the problem.

**Comment by satoren** [comment]
It seems not enough FONS_SCRATCH_BUF_SIZE on 32bit platform.
