### ISSUE TITLE
nvgText and nvgTextBox not support "\t"

### ISSUE THREAD

**Issue by adricoin2010** [memononen/nanovg#389]
Hello, I have a problem.

nvgText does not properly add the tab (\t) and displays an unknown character.

![Tab Problem](http://i66.tinypic.com/9gavs5.png)

My english is bad, I am from Spain.

**Comment by memononen** [comment]
`nvgText` currently tries to render tab as a glyph, that's the box.

How would you expect the tab to work? I see two potential options:
1) It would behave like a space, but longer (html `tab-size`works like this)
2) the tab would snap to nearest tab stop like in text editor

Option 1 would allow you to add longer spate in the text and option 2 would allow you to indent text to specific location.

Both would need some extra code in the API to allow to set the sizes. Option 1 would be easier to implement.

**Comment by adricoin2010** [comment]
Closed issue

I do not know how nanovg works inside, and it is difficult for me to add `"\t"`.

I would like you to add it in the future, something like `nvgTabSize(vg, 4)`.

Thank you.
