### ISSUE TITLE
Linker error: multiple definition of <various functions>

### ISSUE THREAD

**Issue by ne0ndrag0n** [memononen/nanovg#390]
We're evaluating NanoVG for our game's GUI and have run into a problem testing it that looks like it may be a bug. If the header <nanovg_gl.h> is included multiple times in the project (for example, two different .cpp files), the linker will gag at redefinitions of the nvg* GL functions:

```
src/main.o: In function `nvgCreateGL3':
nanovg_gl.h:1553: multiple definition of `nvgCreateGL3'
nanovg_gl.h:1553: first defined here
src/main.o: In function `nvgDeleteGL3':
nanovg_gl.h:1598: multiple definition of `nvgDeleteGL3'
nanovg_gl.h:1598: first defined here
src/main.o: In function `nvglCreateImageFromHandleGL3':
nanovg_gl.h:1611: multiple definition of `nvglCreateImageFromHandleGL3'
nanovg_gl.h:1611: first defined here
src/main.o: In function `nvglImageHandleGL3':
nanovg_gl.h:1635: multiple definition of `nvglImageHandleGL3'
nanovg_gl.h:1635: first defined here
```

Not sure what we're doing wrong, if we're doing anything wrong at all. Here's some background:

- `gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) `
- `GNU ld (GNU Binutils for Ubuntu) 2.27`
- NanoVG is included in the project by having built the original repo in the original NanoVG directory (premake4 and all) and then copying nanovg.a and its headers into our lib directory. NanoVG is then linked into our project using -lnanovg.
- Our project uses a threaded build (make -j8) where .cpp files are built together to .o files in parallel before being linked in a final single stage.
- The error does not occur if <nanovg_gl.h> is only included once, in one .cpp file, in the entire project.
- The error can be supressed with the "-z muldefs" linker option, but we'd prefer not to use this.

**Comment by memononen** [comment]
You should define `NANOVG_GL2_IMPLEMENTATION` only in one file. it follows the stb style [1] one header lib idea.

[1] https://github.com/nothings/stb#why-single-file-headers

**Comment by ne0ndrag0n** [comment]
That fixes it! Thank you for your help.
