### ISSUE TITLE
Change iter.x to iter.nextx as nvgText return.

### ISSUE THREAD

**Issue by adricoin2010** [memononen/nanovg#391]
With `iter.x`, it does not completely cover the last letter. Since it returns the initial position of the last character:

![nvgText with iter.x](http://i68.tinypic.com/2zs7gpz.png)

And with `iter.nextx`:

![nvgText with iter.x](http://i63.tinypic.com/2d1pqxd.png)

The code is:

~~~c++
nvgFontSize(vg, 14.0f);
nvgTextAlign(vg, NVG_ALIGN_LEFT|NVG_ALIGN_TOP);
nvgTextMetrics(vg, NULL, NULL, &lineh);

int x = 100;
int y = 100;

float lenghtText = nvgText(vg, x, y, "LuaBridge offers the following features:", NULL);

float SizeX = lenghtText - x;

nvgBeginPath(vg);
nvgRect(vg, x, y, SizeX, lineh);
nvgFillColor(vg, nvgRGBA(100, 100,255, 100));
nvgFill(vg);
~~~

As you can see, with `iter.nextx` we get the final position of the last character correctly.

~~~c++
float nvgText(NVGcontext* ctx, float x, float y, const char* string, const char* end)
{
	//All code

	//return iter.x; Old return
	return iter.nextx;
}
~~~

My English is bad, sorry.

**Comment by memononen** [comment]
Fixed the return value of `nvgText`. Take a look at `nvgTextBounds`, it is better suited for what you need.

**Comment by adricoin2010** [comment]
Thanks, I close the issue.
