### ISSUE TITLE
Outline of round rect which contains a hole is broken

### ISSUE THREAD

**Issue by omochi** [memononen/nanovg#394]
If round rect contains a hole, its outline is broken.

code and screenshot of bug.

```c++
            nvgBeginPath(ctx);
            nvgPathWinding(ctx, NVG_SOLID);
            nvgRoundedRect(ctx,
                           shadow_rect.origin().x(), shadow_rect.origin().y(),
                           shadow_rect.size().width(), shadow_rect.size().height(),
                           2);
            nvgPathWinding(ctx, NVG_HOLE);
            nvgRect(ctx, 40, 40, 100, 100);
            nvgFillColor(ctx, nvgRGBA(0, 100, 200, 75));
            nvgFill(ctx);
```

<img width="464" alt="hole-in-solid" src="https://user-images.githubusercontent.com/312792/28724587-869b6cce-73f5-11e7-9fc2-ec0e7f8f37b1.png">

If a hole is removed, outline is correct.
this is code and screenshot. 
code is just commented out hole.

```c++
            nvgBeginPath(ctx);
            nvgPathWinding(ctx, NVG_SOLID);
            nvgRoundedRect(ctx,
                           shadow_rect.origin().x(), shadow_rect.origin().y(),
                           shadow_rect.size().width(), shadow_rect.size().height(),
                           2);
//            nvgPathWinding(ctx, NVG_HOLE);
//            nvgRect(ctx, 40, 40, 100, 100);
            nvgFillColor(ctx, nvgRGBA(0, 100, 200, 75));
            nvgFill(ctx);
```

<img width="454" alt="solid" src="https://user-images.githubusercontent.com/312792/28724684-d6dac91e-73f5-11e7-9d65-5f27c5765f52.png">

with a hole case, radius of rounded corder is 5px.
correct value is 4px. (2 point on retina display)
top left corner and bottom left corner is easier to look issue. 

I am creating GUI library and I am using nanovg.
this 1px error stand out in some case.
I want pixel perfect rendering.

**Comment by memononen** [comment]
The winding works as a command like `nvgMoveTo()`. I have to admit, it is inconsistent. It made sense at the time of writing it.

So the correct code would be:
```C
            nvgBeginPath(ctx);
            nvgRoundedRect(ctx,
                           shadow_rect.origin().x(), shadow_rect.origin().y(),
                           shadow_rect.size().width(), shadow_rect.size().height(),
                           2);
            nvgRect(ctx, 40, 40, 100, 100);
            nvgPathWinding(ctx, NVG_HOLE); // turns the rect into a hole
            nvgFillColor(ctx, nvgRGBA(0, 100, 200, 75));
            nvgFill(ctx);
```

**Comment by omochi** [comment]
I changed my code to you said and I got perfect result I expected !
Thank you for advice and sorry my misunderstanding about `nvgPathWinding`.
