### ISSUE TITLE
example_fbo cannot run on certain Mac computers

### ISSUE THREAD

**Issue by AndrewBelt** [memononen/nanovg#410]
I suspect from [this issue](https://github.com/VCVRack/Rack/issues/17) in the VCV Rack repo that the Mac computers supporting up to OpenGL 3.3 on [this list](https://support.apple.com/en-us/HT202823) cannot create framebuffers using `nvgluCreateFramebuffer` in nanovg_gl_util.h. I suspect this is because the graphic cards do not support stencil renderbuffers, but I am not 100% sure.

Is there a way around this? I am not an expert in advanced OpenGL features, so I would be grateful to have any insight into alternatives for supporting these Macs while supporting the feature nanovg requires, since I heavily use framebuffers in my application.

`glCheckFramebufferStatus(GL_FRAMEBUFFER)` returns `GL_FRAMEBUFFER_UNSUPPORTED` inside that function.

**Comment by olliwang** [comment]
For macOS 10.11+, you have an option to use Metal instead of OpenGL. https://github.com/ollix/MetalNanoVG

**Comment by AndrewBelt** [comment]
Interesting! I know little about Metal, but since a nanovg backend exists for it, it would be worth it to try. I'm still interested in an OpenGL workaround, since it would likely be much easier and I wouldn't need to compile two versions of the application (since the OpenGL application uses the MacOS 10.7 SDK for maximum compatibility, but the Metal headers wouldn't be found.)

**Comment by memononen** [comment]
NanoVG requires stencil buffer to work, there's no workaround for that.
IIRC some older graphics cards used to require 24 depth buffer along with
stencil buffer to work.

You could try to create GL_DEPTH24_STENCIL8 buffer if GL_STENCIL_INDEX8
fails.

**Comment by AndrewBelt** [comment]
@memononen I think that does it!! I made a test build and users have reported that GL_DEPTH24_STENCIL8 is supported. I will take your suggestion and patch nanovg_gl_util.h on my end to attempt that after GL_STENCIL_INDEX8 fails.

Do you have a Patreon/donation platform?

**Comment by memononen** [comment]
@AndrewBelt excellent! if it works, please make a PR for the fixes.
