### ISSUE TITLE
How do I render without premultiplied alpha?

### ISSUE THREAD

**Issue by Kerndog73** [memononen/nanovg#414]
I have a screenshot function in my application where I use `glReadPixels` to copy the data from the framebuffer and write it to a PNG file. The problem is that the edges of the shapes where color means transparency doesn't look right. After inspecting the color values of the pixels I am pretty sure this is due to premultiplied alpha. Is there something I can call before `nvgEndFrame` to render without premultiplied alpha?

Thanks

**Comment by memononen** [comment]
Nope, but you can unpremultiply the pixels, see:
https://github.com/memononen/nanovg/blob/master/example/demo.c#L1128

**Comment by Kerndog73** [comment]
Ok thanks memonomen
