### ISSUE TITLE
Drawing of paths only works in Android emulator but not on physical devices

### ISSUE THREAD

**Issue by Pixelfahnder** [memononen/nanovg#432]
Good day everyone,

I discovered a strange behavior: I took the graph drawing from the example and can not run it successfully on three different Android test devices. The line as well as the filled version of the graph is not drawn correctly (the filled version is ommitted on the screenshots). It works in the emulator when it is set up to mimik a Nexus 7. Also it does not work on a real Nexus 7. The behaviour on the physical devices is all the same. Do you have any hints why this behaviour occurs?

_The screenshots show the OpenGL ES 2 support of the different devices as well as the actual supported OpenGL ES version._

[Nexus 7 emulator, Android 7.1.1] **(this is the way it is supposed to look like)**
![image](https://user-images.githubusercontent.com/18440933/32439209-01f82c44-c2ee-11e7-9eb9-d62f016399af.png)

[Galaxy Note 3, Android 5.0]
![image](https://user-images.githubusercontent.com/18440933/32439475-350d9a96-c2ef-11e7-8e3c-412f51719c93.png)

[Trekstore  Surftab Breeze 7.0 Quad LTE, Android 7.0]
![image](https://user-images.githubusercontent.com/18440933/32439492-4f3bfd22-c2ef-11e7-8d51-fba4f939ef16.png)

**Comment by memononen** [comment]
NanoVG needs stencil buffer for rendering. Check your OpenGL initialization.

**Comment by Pixelfahnder** [comment]
@memononen I don't believe that that is the problem because it is the same APK that is running differently on the different devices. If it should be the lack of the Stencil buffer initialization it shouldn't work in the emulator either, correct?

**Comment by memononen** [comment]
I don't know about APKs, but that big rectangle is always the symptom of not having a stencil buffer, or less frequently, not clearing the stencil buffer. Check that too.

**Comment by Pixelfahnder** [comment]
@memononen I will. So the APK is the compiled APP version on Android which means the same binary code on all devices if you use the same APK on every device which is weird. So the only thing that may cause this is that some devices like the emulator may have turned on the stencil buffer on per default while others don't.

**Comment by Pixelfahnder** [comment]
@memononen It seems that you were right and my expectation about the different devices is also correct. I rechecked my OpenGL ES initialization for the stencil buffer part and it did not initialize it correctly which was my fault. But as the emulator had it working it seems that the emulator may have some kind of default initialization in place. Thank you very much for the help.
