### ISSUE TITLE
Can't initialize GL2 on High Sierra: EXC_BAD_ACCESS during glCreateProgram

### ISSUE THREAD

**Issue by BusFactor1Inc** [memononen/nanovg#454]
When I try the following program on macOS High Sierra:

int main(int argc, char (**argv))
{
        struct NVGcontext *(ctx) = (nvgCreateGL2(NVG_ANTIALIAS));
}

I get an EXC_BAD_ACCESS during glCreateProgram:

```
Process 28780 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00007fff51a4977d libGL.dylib`glCreateProgram + 13
libGL.dylib`glCreateProgram:
->  0x7fff51a4977d <+13>: movq   (%rax), %rdi
    0x7fff51a49780 <+16>: popq   %rbp
    0x7fff51a49781 <+17>: jmpq   *0x12b0(%rax)

libGL.dylib`glAttachShader:
    0x7fff51a49787 <+0>:  pushq  %rbp
Target 0: (logo) stopped.
```

Any ideas?

**Comment by lieff** [comment]
You can't just call nvgCreateGL2. You must initialize opengl first using native/glfw/sdl and glew/glad/etc loaders. See example_gl2.c example, but it can need modifications for macos.

**Comment by BusFactor1Inc** [comment]
Ok. Thank you.
