### ISSUE TITLE
android example?

### ISSUE THREAD

**Issue by Mis012** [memononen/nanovg#458]
Hello,
in the issues, several people seem to talk about using nanovg on android like it was nothing.
However, the examples all use glfw, which is not available on android. Someone was making SDL port (judging from the issues), but didn't share it anywhere. And the bgfx port is plagued with c++, and their 'c99 api' doesn't extend to nanovg, that they felt the need to c++-ize as well. What is it that I am missing? Why can't I just make a simple app for android without using java?
Can someone please help me understand how to use nanovg on android? Just drawing, touch and ideally keyboard, but I guess I would rather make my own keyboard then use c++ just because bgfx author does. Sorry to bother you, but it seems like making C apps shouldn't be as difficult as it seems to me right now.
Thanks for help :)

**Comment by Mis012** [comment]
Of course this won't matter if I can get glfw port to work, but that's dependent on wheather it doesn't work now because of a bug that can be solved, or for another reason that can't be controlled.

**Comment by Mis012** [comment]
thanks, ill look into it :)

**Comment by AndreyArsov** [comment]
The easiest will be to use the samples from the NDK that show how to use OpenGL, and then replace the GL code with NanoVG. Just you have to have stencil buffer as follows:

    public GLES3JNIView(Context context, AttributeSet attrs) {
        super(context, attrs);

        // Pick an EGLConfig with RGB8 color, 16-bit depth, 8-bit stencil,
        // supporting OpenGL ES 2.0 or later backwards-compatible versions.
        setEGLConfigChooser(5, 6, 5, 0, 16, 8);
        setEGLContextClientVersion(2);
        setRenderer(new GLRenderer(this));
    }

When creating the NanoVG context, just use the GLES option.

**Comment by lieff** [comment]
Yes, full native activity is tricky. Consider initialize opengl in java, and use JNI to call native nanovg code.

**Comment by Mis012** [comment]
Ok, so I have downloaded SDL and I tried to use this code:
```C
 #include <stdio.h>
 #include <stdlib.h>
 #include <android/log.h>
 #include <GLES2/gl2.h>
 #include "SDL.h"
 #define GLFW_INCLUDE_ES2
 #define NANOVG_GLES2_IMPLEMENTATION
 #include "nanovg.h"
 #include "nanovg_gl.h"
 #include "nanovg_gl_utils.h"

int SDL_main(int argc, char **argv) { 
  SDL_Window *window = NULL;
  SDL_GLContext context;
  SDL_Event event;
  NVGcontext* vg = NULL;
  
    int flags = SDL_INIT_EVERYTHING & ~(SDL_INIT_TIMER | SDL_INIT_HAPTIC);
    if (SDL_Init(flags) < 0)
    {
    	__android_log_print(ANDROID_LOG_ERROR, "SDL-my-main", "error: sdl2 init failed: %s", SDL_GetError());
        return 1;
    }
    
    SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);

    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);

    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
    SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS, 1);
    SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, 8);
    window = SDL_CreateWindow("Example", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 1024, 800,
        SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE | SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI);
    if (!window)
    {
        SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS, 0);
        SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, 0);
        window = SDL_CreateWindow("Example", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 1024, 800,
            SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE | SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI);
        if (!window)
        {
            __android_log_print(ANDROID_LOG_ERROR, "SDL-my-main", "error2: sdl2 init failed: %s", SDL_GetError());
            return 1;
        }
    }
    context = SDL_GL_CreateContext(window);
    SDL_GL_MakeCurrent(window, context);
    
    vg = nvgCreateGLES2(NVG_ANTIALIAS | NVG_STENCIL_STROKES | NVG_DEBUG);
    if (vg == NULL) {
        __android_log_print(ANDROID_LOG_ERROR, "SDL-my-main", "error: nanovg init failed");
        return 1;
    }
    
    nvgBeginPath(vg);
	nvgRect(vg, 100,100, 120,30);
	nvgFillColor(vg, nvgRGBA(255,192,0,255));
	nvgFill(vg);
    
    int quit=0;
    while (!quit)
    {

        SDL_PollEvent(&event);

        switch(event.type)
        {
        case SDL_QUIT:
          quit=1;
          break;
        }
        nvgBeginPath(vg);
	nvgRect(vg, 300,100, 120,30);
	nvgFillColor(vg, nvgRGBA(255,192,0,255));
	nvgFill(vg);
    }
    
    return 0;
 }
```
And I am getting error: `SDL-my-main: error2: sdl2 init failed: Could not initialize OpenGL / GLES library`
What can be done about that?

**Comment by lieff** [comment]
Does bundled examples works? If you get latest SDL, there can be problems like https://github.com/ggez/ggez/issues/70#issuecomment-335467629 , https://forums.libsdl.org/viewtopic.php?p=39573
Note that in java init case you do not need SDL.

**Comment by lieff** [comment]
Also you must change
```

    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
```
Android have GLES v1/v2/v3, not OpenGL 2.x/3.x/4x.

**Comment by Mis012** [comment]
@lieff thanks, that was the reason, `SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);` works.
But it doesn't display anything but black screen, even though there is no error, so nvgCreateGLES2 must have been successful?

**Comment by Mis012** [comment]
this works: https://github.com/ennorehling/android-sdl/blob/master/jni/src/main.c

**Comment by lieff** [comment]
This ^^ is not glsl example. Also I do not see where you swap buffers in your example.

**Comment by Mis012** [comment]
guess I'll have a read about buffer swapping then :D

**Comment by lieff** [comment]
SDL_GL_SwapWindow();

**Comment by memononen** [comment]
You will also need to call nvgBeginFrame() nvgEndFrame() see the example
code.

**Comment by Mis012** [comment]
SDL_GL_SwapWindow(window); added. No difference. is there something else I am missing?

**Comment by Mis012** [comment]
aah sorry I see

**Comment by Mis012** [comment]
IT LIVES! thanks for help. I'll comment 'my' code and will put it on my github with a link here, then close the issue I guess. What license is appropriate? I like GPL, but it may be too bold for an example

**Comment by Mis012** [comment]
Ok, the example is here: https://github.com/Mis012/nanovg-with-SDL-on-android
