### ISSUE TITLE
Y Axis: upside down text and textures

### ISSUE THREAD

**Issue by RandomErrorMessage** [memononen/nanovg#462]
When trying to interact directly with NanoVG framebuffers I notice everything is drawn upside down, including text. The framebuffer is only flipped on an actual frame draw. Why is it like this? Is there any way to avoid this issue?

If it was a matter of just drawing from the bottom-left instead of my normal top-left I could work around this, but clearly this is intended based on how text is drawn.

**Comment by memononen** [comment]
NanoVG has origin at upper left.

There's some weirdness in opengl whether the origin is upper-left or lower-left (or was it with data storage) when using render target as texture. I always forget what it is.

For example the NanoVG frame buffer code flips the Y coordinate when the FBO use used as texture, see:
https://github.com/memononen/nanovg/blob/master/src/nanovg_gl_utils.h#L66

**Comment by RandomErrorMessage** [comment]
After some more experimentation it might be the library (SDL_gpu) I'm trying to use this in combination that might be doing things upside down.

Once I work out the finer aspects hopefully I'll have the time to submit some example code.
