### ISSUE TITLE
How do you implement getImageData interface?

### ISSUE THREAD

**Issue by whpskyeagle** [memononen/nanovg#463]
The H5 canvas standard contains the getImageData interface. How does nanovg support it? Nanovg is actually drawn at EndFrame.

**Comment by memononen** [comment]
You should use what opengl provides. Take a look at the screenshot code in the example.

**Comment by whpskyeagle** [comment]
nvgBeginFrame

nvgBeginPath
nvgMoveTo
nvgLineTo
nvgFill   A

nvgBeginPath
nvgMoveTo
nvgLineTo
nvgFill   B

nvgEndFrame

/// If I call glReadPixel here, I can screenshot.
/// But I want to call getImageData at between A and B。
/// Like this:

nvgBeginFrame

nvgBeginPath
nvgMoveTo
nvgLineTo
nvgFill   A

data = getImageData
draw use data

nvgBeginPath
nvgMoveTo
nvgLineTo
nvgFill   B

nvgEndFrame

Nanovg is actually drawn at EndFrame，so it's wrong to call getImageData before EndFrame.

**Comment by memononen** [comment]
If you want to use the image as part of rendering, then you need to render
the image to a render target. That way the image always stays on GPU. Take
a look at the example_fbo.
