### ISSUE TITLE
Drawing a FBO to another FBO results in blurriness

### ISSUE THREAD

**Issue by RandomErrorMessage** [memononen/nanovg#464]
Drawing an FBO to another FBO results in blurriness, especially noticeable with text, example below. This doesn't happen if you're drawing a FBO directly to the screen, only when you draw a FBO to another and then to the screen. Something to do with blending? The shader?

![image](https://user-images.githubusercontent.com/35673979/37502665-518b64fc-2891-11e8-8382-83a5c71fd863.png)

**Comment by memononen** [comment]
Looks like you are using bilinear filtering and rendering half a pixel off. Things get blurry. How do you draw to the second fbo?

**Comment by RandomErrorMessage** [comment]
You were correct about it being a sub-pixel issue. Thanks a ton!
