### ISSUE TITLE
Thoughts on text rendering performance

### ISSUE THREAD

**Issue by xeekworx** [memononen/nanovg#466]
The source docs don't give much information, but based on what little code I've read, is it true that nanovg allocates a new texture atlas every time I draw text?

No? Then will a new texture atlas get created if I call nvgFontSize? Maybe I should avoid calling this very much?

**Comment by memononen** [comment]
NanoVG caches a glyph for each typeface/size (size is quantized to one decimal place). If you render same size text all the time, then it should not be a problem.

If you see atlasses create each frame, then that is a bug. I'd appreciate a repro case for that.

**Comment by xeekworx** [comment]
Thanks, that's what I was hoping for, it just didn't look that way when I was trying to read the code.
I'm planning to run some performance tests next weekend since my bitmapfont library is just about done and I wanted to make comparisons between nanovg's text rendering, sdl_ttf, and my own. I suspect sdl_ttf will probably be the worst.
