### ISSUE TITLE
Antialiasing-induced seams when tiling

### ISSUE THREAD

**Issue by borodust** [memononen/nanovg#487]
When drawing rectangles back to back filled with either a solid color or an image paint and enabled antialiasing, background sips through seams: 

https://vimeo.com/273192938

I can avoid this behavior by either disabling antialiasing completely or by discarding fractional part of numbers passed to `nvgTranslate`. Is there any other way to avoid this issue?

**Comment by memononen** [comment]
This is common problem with the type of anti-aliasing NanoVG uses. Other programs suffer from it too i.e. http://www.inkscapeforum.com/viewtopic.php?t=13741. One solution is to expand the rectangles a bit, or use MSAA.

**Comment by borodust** [comment]
Understood, thank you! I guess, I would go for MSAA.
