### ISSUE TITLE
nvgCreateImageMem() creates black square, no errors

### ISSUE THREAD

**Issue by otoomey** [memononen/nanovg#488]
_I am using the LWJGL bindings for NanoVG_. 

While I am using the Java bindings for NanoVG, the issue I am having is related directly to the library itself.

I want to create a NanoVG image from a `ByteBuffer`, in order to draw it on the screen using the `nvgCreateImageMem` method. This is because I want to load the image asynchronously, something which cannot be achieved using nvgCreateImage. The picture, a PNG, is read into a `ByteBuffer`, flipped, then given to NanoVG. However, when I use it to fill a rectangle on the screen, it just appears as solid black.

The signature in the bindings I am using for `nvgCreateImageMem` is:
```(java)
int nvgCreateImageMem(long ctx, int imageFlags, ByteBuffer data)
```

Here is the contents of the `ByteBuffer`:
```
-119 80 78 71 13 10 26 10 0 0 0 13 73 72 68 82 0 0 0 48 0 0 0 48 8 4 0 0 0 -3 11 49 12 0 0 0 -56 73 68 65 84 88 -61 -19 -106 75 10 -61 48 12 5 5 57 100 126 -89 75 106 66 15 105 -104 46 10 37 -115 67 44 -39 -54 -94 -59 111 109 -49 -128 -80 31 18 105 105 105 -7 -37 -48 17 -24 -43 -89 103 86 58 27 -2 9 68 -99 -126 -103 8 108 6 5 -127 119 34 -125 18 15 -16 -48 11 -122 -49 -91 -116 98 -121 -113 -6 -111 -86 21 -59 -8 68 49 -70 -29 69 68 24 -81 20 -43 -8 107 -123 11 62 81 76 -18 120 17 17 -90 -93 -62 21 -97 42 -36 -15 -119 -62 31 127 24 -53 29 -8 68 -31 -113 -65 93 112 -13 -120 -66 94 78 -44 55 109 9 -66 -41 55 109 17 -34 86 -26 69 120 93 -45 86 -31 -13 77 91 -115 119 81 -28 59 -25 -68 105 -35 -16 -25 77 -21 -118 -81 80 -80 -22 -1 -21 78 -79 88 22 -81 -51 -68 120 5 -21 110 103 91 29 23 19 -66 -91 -91 -27 -57 -14 2 97 52 95 56 -6 -23 5 -103 0 0 0 0 73 69 78 68 -82 66 96 -126
```

[Here](https://raw.githubusercontent.com/google/material-design-icons/master/navigation/drawable-xhdpi/ic_close_white_24dp.png) is the actual image.

When I write the `ByteBuffer` out to a file, and then load it using `nvgCreateImage`, the picture is displayed correctly.

As the title says, no error or warning is printed to the console.

I think that one of two things could be happening; the first being far less likely than the second:
1. There is actually a bug in `nvgCreateImageMem()`
2. `nvgCreateImageMem()` wants the image data to be in a certain format that my `ByteBuffer` is not in. If this is the case, what format should it be in? The required format is perhaps something that could be clearer in the documentation.

**Comment by memononen** [comment]
`nvgCreateImageMem()` expects same data format as `nvgCreateImage()`. They both return 0 in case creating the image failed.

I dont know what ByteBuffer does. What is the actual code you use to get stuff from ByteBuffer and pass it to NanoVG? What does flipping the buffer mean?

**Comment by otoomey** [comment]
Thank you for your fast response. I will try to answer your questions and follow up on your points:

> They both return 0 in case creating the image failed.

**nvgCreateImageMem() does not return 0.** Instead, it returns 3.

> I dont know what ByteBuffer does.

[Here](https://github.com/LWJGL/lwjgl3-wiki/wiki/1.3.-Memory-FAQ) is an explanation of `ByteBuffer` and what its used for:
_"The easiest way to think of ByteBuffer is as a wrapper over a native C pointer, plus the array length (the buffer.capacity()). LWJGL maps C primitive types to the corresponding class in java.nio. Arrays of pointers are mapped to the org.lwjgl.PointerBuffer class. Pointers to structs are mapped to the corresponding struct class. Pointers to struct arrays are mapped to the corresponding <StructClass>.Buffer class. PointerBuffer and the struct Buffer classes have an API very similar to java.nio buffers."_


> What is the actual code you use to get stuff from ByteBuffer and pass it to NanoVG?

The data is read from a file into the `ByteBuffer` like so:
```(java)
try (SeekableByteChannel byteChannel = Files.newByteChannel(path)) {
            buffer = createByteBuffer((int) byteChannel.size() + 1);
            while (byteChannel.read(buffer) != -1);
}
buffer.flip()
```
I am using this method of reading the file to load _font_ files for NanoVG; and it works perfectly.

The binding take the `ByteBuffer` as an argument, and then runs the following:
```(java)
nvgCreateImageMem(ctx, imageFlags, memAddress(buffer), buffer.remaining());
```
`memAddress()` is part of [MemoryUtil](https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/core/src/main/java/org/lwjgl/system/MemoryUtil.java). 

[Here](https://gyazo.com/033fa815fdcbbe644a99198addc6fda1) is the screenshot of the black square. If I use `nvgCreateImage()` instead, the icon renders correctly, as you can see [here](https://gyazo.com/aa638a94bc874b83dc58cecc7e6d3329).

**Comment by otoomey** [comment]
I have discovered the cause of the problem:
**You cannot create images on a separate thread, they must be created on the main thread**

If you try to create images on a separate thread from the active context thread, you will get a full black or full white image, _and no error will occur._

**Comment by otoomey** [comment]
To people seeing this in the future:
Make sure you fully understand the discrepancy between `nvgCreateImageMem()` and `nvgCreateImageRGBA()`. Under the hood, `nvgCreateImage()` loads an image using stb, and then creates the image using the _latter_ of these two methods. This is something that surprised me when trying to solve the issue I was having above. If you use the wrong method, you will probably get funny (i.e. undesirable) results.
