### ISSUE TITLE
fatal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory

### ISSUE THREAD

**Issue by navaneeth-dev** [memononen/nanovg#504]
i tried building nanovg in vs2017

and get this error: atal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory

**Comment by lieff** [comment]
This page looks like outdated, for vs2017 different instruction needed. But yeah, for vs2017 you must setup each new lib with msbuild manually (like Windows SDK and other SDK's). There things like https://docs.conan.io/en/latest/howtos/vs2017_cmake.html#visual2017-cmake-howto to make process more easy, but it's not official.

You can also use cygwin/msys2 and mingw - they have glew package.
Alternatively you can use glad which you can embed into project as glad.c glad.h. Here example using nanovg with glad: https://github.com/lieff/lvg/blob/master/render/render_nanovg.c
