### ISSUE TITLE
What does c mean in cpaths, ccalls or cverts?

### ISSUE THREAD

**Issue by JrekJarowski97531** [memononen/nanovg#522]
What does c mean in cpaths, ccalls or cverts?

**Comment by memononen** [comment]
Capacity, that is, how much space is actually allocated. n means how many are used.

**Comment by JrekJarowski97531** [comment]
Thanks for an answear. I have got one more question. What is inner and outer color?

**Comment by JrekJarowski97531** [comment]
Thanks for an answer. I have got one more question. What is inner and outer color?

**Comment by memononen** [comment]
They are for gradients. All gradients are rendered using rounded rectangle distance field (linear and radial are special cases of that). So inner is the color closer to the center and it blends into outer color.

**Comment by JrekJarowski97531** [comment]
Thank you. Have you got any online resources? I have so many questions.
