### ISSUE TITLE
Trying to use nvgLoadImageRGBA

### ISSUE THREAD

**Issue by SNSTRUTHERS** [memononen/nanovg#534]
In my code, I'm trying to import images into NanoVG through the use of SDL_Surfaces:

`SDL_Surface *s = {...};`
`img_id = nvgCreateImageRGBA(nvg_ctx, s->w, s->h, 0, (unsigned char*)(s->pixels));`
...
`int w, h;`
`nvgImageSize(nvg_ctx, img_id, &w, &h);`
`nvgImagePattern(nvg_ctx, x + (w/2.f), y + (h/2.f), w, h, 0.f, img_id, 1.f);`

Yet it doesn't seem to be rendering anything to the screen.

**Comment by memononen** [comment]
Image pattern defines fill, you will need to also render a shape.

su 10. maalisk. 2019 klo 21.39 Simon NE Struthers <notifications@github.com>
kirjoitti:

**Comment by SNSTRUTHERS** [comment]
![image](https://user-images.githubusercontent.com/31030033/54157111-e4c22f00-4404-11e9-86ce-ed471d04fefa.png)

Tried to fix it with what you've said, and this is what it looks like.

Here's the code I'm using to try and draw an SDL_Surface onto the screen. (I'm doing this b/c there isn't any text outline support, so I have to do it the hard way)

![image](https://user-images.githubusercontent.com/31030033/54157399-76ca3780-4405-11e9-94d2-72ad2602b918.png)

**Comment by SNSTRUTHERS** [comment]
There are no errors printed out to the console. I've checked the actual pixel data, and it does exist. I even tried converting the pixel format to RGBA32. Which pixel format is needed when importing to nvgCreateImageRGBA?

**Comment by memononen** [comment]
The image pattern call does not look correct. You define the pattern in "world space", the same space as your rectangle. So in order to make a pattern to fill the rectangle, it should look something like:
```C
		imgPaint = nvgImagePattern(vg, x, y, w,h, 0.0f, image, 1.0f);
		nvgBeginPath(vg);
		nvgRect(vg, x,y, w,h);
		nvgFillPaint(vg, imgPaint);
		nvgFill(vg);
```

**Comment by SNSTRUTHERS** [comment]
Tried it out. Still produces a black box.

![image](https://user-images.githubusercontent.com/31030033/54158428-b8f47880-4407-11e9-83b6-a940e0e572e7.png)

**Comment by memononen** [comment]
Did not spot that delete image there in the first time. The stuff is sent to opengl at `nvgEndFrame`, since you delete the texture immediately, you will get black texture.

**Comment by SNSTRUTHERS** [comment]
It works! Thank you! 👍
