### ISSUE TITLE
a couple of questions

### ISSUE THREAD

**Issue by HendrixString** [memononen/nanovg#544]
hi, great project

I have a few questions:
1. with what API does the opengl context is acquired internally ?
2. what is the best practice  to integrate this into a window system ? maybe even SDL
3. how are the vector graphics rendered ? distance map fields ? what is the technique ?

cheers
Tomer

**Comment by mulle-nat** [comment]
I set the window stuff up with glfw and then use nannovg to draw in the window. (See: https://github.com/mulle-kybernetik-tv/MulleGLExample/blob/4315b15e1bc1d5cc52f8ec2ef29bf534dd7a067c/src/main.m). I don't know if that is best practice, nor would I care :)

Can't answer #3, I am just using the functionc calls :)
