### ISSUE TITLE
There's no method to draw triangles

### ISSUE THREAD

**Issue by ngoduyanh** [memononen/nanovg#545]

**Comment by orange451** [comment]
Yes there is.

**Comment by timmyd7777** [comment]
I will try to give a more helpful answer.  This will draw a filled or outlined triangle with vertices at (aX,aY), (bX,bY), (xY,cY):

void nvgDrawTriangle ( NVGcontext context, float ax, float aY, float bX, float bY, float cX, float cY, bool fill )
{
  nvgBeginPath ( context );
  nvgMoveTo ( context, aX, aY );
  nvgLineTo ( context, bX, bY );
  nvgLineTo ( context, cX, cY );
  if ( filled )
    nvgFill ( context );
  else
    nvgStroke ( context );
}

**Comment by ngoduyanh** [comment]
I already found the way to draw triangles a while ago, but I forgot to close the issue. Thanks for replying btw.
