### ISSUE TITLE
Wobbly text near top edge of display

### ISSUE THREAD

**Issue by mattkille** [memononen/nanovg#570]
I'm observing wobbly text (characters out by 1 pixel on y-axis) when drawn at or near the top-most edge of the display. The following snippet of code demonstrates this:

      for (int x = 0, y = -5; y < height; x += 80, y++)
      {
         char txt[30];

         if (x > width - 80)
         {
            x = 0;
            y += 31;
         }

         sprintf(txt, "(y = %d)", y);
         nvgFontFace(vg, "sans");
         nvgFontSize(vg, 15.0f);
         nvgTextAlign(vg, NVG_ALIGN_LEFT | NVG_ALIGN_TOP);
         nvgFillColor(vg, nvgRGBA(0, 0, 0, 255));
         nvgText(vg, x, y, "feedback", NULL);
         nvgText(vg, x, y + 16, txt, NULL);
      }

Result seen in the following enlarged image. At this particular font size, positions y=-1 to y=1, show the wobbly text result. But other font sizes have a similar effect at different ranges of positions, all near the y=0 position.

![wobbly](https://user-images.githubusercontent.com/62154049/76647746-4b68b400-6555-11ea-856e-8e17c1ed3285.png)

**Comment by mattkille** [comment]
The issue appears to be pre-transformation, as swapping the above _nvgText()_ calls with the following results in **all** the text having this problem:

```
      nvgSave(vg);
      nvgTranslate(vg, i, y);
      nvgText(vg, 0, 0, "feedback", NULL);
      nvgText(vg, 0, 16, txt, NULL);
      nvgRestore(vg);
```

**Comment by mattkille** [comment]
Problem appears to originate in fontstash; though I can't be sure of the original intention of the author so the same modification might equally be made in a different location. (Such as making font metrics like ascent whole numbers where these are grid fit aligned.)

It looks like the consequence of cropping a float as an int using a cast when values cross the positive/negative boundary. In this case we have short and tall glyphs with different negative yoff values. These whole numbers are added to a slightly smaller float y position, with fraction, resulting in either a small negative float (tall glyphs) or positive float (small glyphs.) The cast is rounding _up_ the negative value and rounding _down_ the positive, resulting in the characters being drawn +/- 1 pixel out of step from each other.

As I say, I wasn't certain of the original intention of the code, so I chose a fix that seemed like the nearest thing, namely to change the cast to a call to floor().

```
--- nanovg/src/fontstash.h	Wed Mar 11 21:12:37 2020
+++ nanovg/src/fontstash.h	Wed Mar 18 11:13:38 2020
@@ -1228,2 +1228,2 @@ static void fons__getQuad(FONScontext* stash, FONS
-		rx = (float)(int)(*x + xoff);
-		ry = (float)(int)(*y + yoff);
+		rx = floor(*x + xoff);
+		ry = floor(*y + yoff);
@@ -1241,2 +1241,2 @@ static void fons__getQuad(FONScontext* stash, FONS
-		rx = (float)(int)(*x + xoff);
-		ry = (float)(int)(*y - yoff);
+		rx = floor(*x + xoff);
+		ry = floor(*y - yoff);
```
Another option would perhaps be to round the input _y_ value at an earlier stage. But I assumed the '(float)(int)' cast was there expecting to deal with fractions.

**Comment by memononen** [comment]
Thanks for looking into it. The intent is to remove the fractional part to make sure the glyphs are rendered at whole pixels to keep the glyphs from blurring. Floor indeed is the right solution here.
