### ISSUE TITLE
Question Regarding UTF-16 emojis

### ISSUE THREAD

**Issue by orange451** [memononen/nanovg#617]
I read that NanoVG font rendering expects UTF-8 formatted text. However, most emojis are UTF-16. Take for example, the poop emoji:
\uD83D\uDCA9
how can this be rendered within NanoVG? I tried loading in the font NotoColorEmoji, but when trying to draw the above character, nothing is drawn. UTF-8 characters render totally fine, however.

**Comment by mulle-nat** [comment]
[https://onlineutf8tools.com/convert-utf16-to-utf8](https://onlineutf8tools.com/convert-utf16-to-utf8)
