### ISSUE TITLE
Problem of nvgImagePattern

### ISSUE THREAD

**Issue by BusyStudent** [memononen/nanovg#629]
It there any way to use a part of image as pattern? not the whole image.

**Comment by mulle-nat** [comment]
That's pretty vague. The answer is probably NO.

I assume you mean you want to use only a certain rectangle of an image as the fill ? You could do this by "zooming" into the imagePattern, with the `nvgImagePattern` function like in this test:

![grafik](https://user-images.githubusercontent.com/1381995/167011471-05c3247c-42b3-4ef5-9c79-8806038fd844.png)

The math to get this to do exactly what you want, might be too tricky to be useful though.

Also it may not look so great. In this test case, there are non-transparent pixels in the image borders. So the clamping of OpenGL makes the ugly green line. 

You couldn't get a replicating pattern out of the image, as `NVG_IMAGE_REPEATX|NVG_IMAGE_REPEATY` applies to the whole image. 

At least that's how I understand it. I am not a graphics authority :smile: 

---

The [header declaration](https://github.com/memononen/nanovg/blob/master/src/nanovg.h#L420) of the function is misleading, as `ex` `ey` should be `w` `h`.

``` c
NVGpaint nvgImagePattern(NVGcontext* ctx, float ox, float oy, float ex, float ey,
						 float angle, int image, float alpha);
```

As they are in the [source file](https://github.com/memononen/nanovg/blob/master/src/nanovg.c#L939) file.

``` c
NVGpaint nvgImagePattern(NVGcontext* ctx,
								float cx, float cy, float w, float h, float angle,
								int image, float alpha)
```

**Comment by BusyStudent** [comment]
Yes. Using zooming is the way I was using for slove it.too tricky   

But it cannot use RepeatX and RepeatY

Maybe we should add a api like ```nvgSubImagePattern```  @memononen ? 

Is it possible to implement it in nanovg?

**Comment by mulle-nat** [comment]
Just for posterity, it is possible to do it and I have done it. But it is fairly complicated. Basically you have to compute the inverse transform of what nanovg will be doing and then modify it. It's part of [MulleUI](https://github.com/MulleUI), which should see the light of day this century...
