### ISSUE TITLE
`'nvgCreateGL3’ was not declared in this scope`

### ISSUE THREAD

**Issue by tree786isback** [memononen/nanovg#634]
I am defining this in one of my cpp files:
```c++
#include <nanovg.h>
#define NANOVG_GL3_IMPLEMENTATION
#include <nanovg_gl.h>
```
But when I come to init my nanovg context (in the same cpp file), like this:
```c++
nanovg_context = nvgCreateGL3(NVG_ANTIALIAS | NVG_STENCIL_STROKES | NVG_DEBUG);
```
It throws an error upon compiling:
```c++
error: ‘nvgCreateGL3’ was not declared in this scope; did you mean ‘nvgCreateFont’?
  137 |   nanovg_context = nvgCreateGL3(NVG_ANTIALIAS | NVG_STENCIL_STROKES | NVG_DEBUG);
      |             ^~~~~~~~~~~~
      |             nvgCreateFont

```
Any ideas why this is happening? I.e. I have clearly defined both `NANOVG_GL3_IMPLEMENTATION` and included `nanovg_gl.h`, so why does it still fail to find `nvgCreateGL3`?

**Comment by mulle-nat** [comment]
Looks like you are including `<nanovg_gl.h>` in some other place before it hits your code, or there is a typo in your code. If you can't see it easily, run the C preprocessor over your source file and see what's happening.

**Comment by tree786isback** [comment]
> Looks like you are including `<nanovg_gl.h>` in some other place before it hits your code

Ah yeah, that's why. Didn't think including it in my hpp header would cause it to throw that error. Thanks for spotting it!
