### ISSUE TITLE
nvgTextBounds doesn't calculate for spaces at the end of a string

### ISSUE THREAD

**Issue by senxd** [memononen/nanovg#636]
Given text such as "abc ", nvgTextBounds doesn't include the space at the end. I assume this is an intentional feature. Is there any other way to get the bounds of the text including space besides appending another space if there is one at the end?

**Comment by mulle-nat** [comment]
Looking at the source, the calculation for the spacing is done by `fons__tt_getGlyphKernAdvance`:

``` c
int fons__tt_getGlyphKernAdvance(FONSttFontImpl *font, int glyph1, int glyph2)
{
	FT_Vector ftKerning;
	FT_Get_Kerning(font->font, glyph1, glyph2, FT_KERNING_DEFAULT, &ftKerning);
	return (int)((ftKerning.x + 32) >> 6);  // Round up and convert to integer
}
```

So the answer should lie with FreeType (or stb_truetype) I believe.

**Comment by senxd** [comment]
Ah. I see. I just made a simple workaround by appending a space if needed. Thanks!

**Comment by mulle-nat** [comment]
I revise my answer here. Actually I think `nvgTextBounds` is buggy. There is a difference how the text bounds are calculated and how the actual drawing is then performed.This shows up most noticeably with the surrounding spaces. The way to get the proper width is to use `nvgTextGlyphPositions` and accumulate the glyphs width.

In this picture you can see how in the third line "  Space around ", you can see the actually emitted spaces and notice how the blue enclosing rectangle (uses `nvgTextGlyphPositions`)  is perfect: 

![image](https://user-images.githubusercontent.com/1381995/182958792-505da19f-3ab9-407c-a0bf-fa89d45cae6a.png)

_You can also see that there is still a problem with the right alignment in my code :smile:_

**Comment by mulle-nat** [comment]
I use `nvgTextGlyphPositions` instead of `nvgTextBounds`, or what do you mean ?
