### ISSUE TITLE
Manually loading images / Generating custom MipMaps for images

### ISSUE THREAD

**Issue by senxd** [memononen/nanovg#637]
Is there a way to generate the opengl textures manually, and pass the textureID to nanovg? I tried doing this, but it is just the color of the paint.

**Comment by senxd** [comment]
Also a note, I haven't spent too much time looking at how NanoVG controls textures, but I assume it looks up the texture in it's internal database or something like this. A workaround is to load the image as you usually would and then update it.

**Comment by mulle-nat** [comment]
I think [these functions](https://github.com/memononen/nanovg/blob/master/src/nanovg_gl.h#L59=) are what you are looking for:
Create the OpenGL texture pass it to `nvglCreateImageFromHandle...` then use the returned value as the image for nanovg calls.

**Comment by senxd** [comment]
Thanks!
