### ISSUE TITLE
Disable blend for certain paths

### ISSUE THREAD

**Issue by senxd** [memononen/nanovg#638]
Is there a way to disable blending (glEnable/glDisable(GL_BLEND) for certain paths? I want to disable this for images

**Comment by mulle-nat** [comment]
The `GL_BLEND` is enabled in [nanovg_gl.h#L1192](https://github.com/memononen/nanovg/blob/master/src/nanovg_gl.h#L1192=), you could turn it off in the source code first, to see if that gives the desired effect. `nvgEndFrame` calls `glnvg__renderFlush`, via NVGparams. You'd have to hack something to make this configurable.

**Comment by senxd** [comment]
From what I saw, that is the only way. Thanks.

**Comment by mulle-nat** [comment]
My answer was just for technically disabling `GL_BLEND`, I think you can probably achieve the effect you want with `nvgGlobalCompositeOperation` or `nvgGlobalCompositeBlendFuncSeparate`.
