### ISSUE TITLE
outlines don’t draw properly

### ISSUE THREAD

**Issue by ColleagueRiley** [memononen/nanovg#648]
I have a simple SVG file (included), that draws a transparent rect with a red stroke, making a rectangle outline. For some reason when I load it it draws the outline on a gray rect.

```cpp
image = nsvgParseFromFile("rect.svg", "px", 96);

rast = nsvgCreateRasterizer(); // create rasterzing object for "flattening"

unsigned char* img = (unsigned char*)malloc(rect.w*rect.h*4); // make data with room for the image

nsvgRasterize(rast, image, 0,0,1, img, w, h, w*4); // load the flattened image into the data
```

![rect](https://user-images.githubusercontent.com/50218871/189793333-9ee502b6-dc3f-4ee4-89a3-63c59b1ddcda.svg)

**Comment by ColleagueRiley** [comment]
After testing it again, it does draw. But, it doesn't draw transparently as it should. 
![Screenshot_2022-09-12_22-28-11](https://user-images.githubusercontent.com/50218871/189793610-abd68833-c8e0-47aa-b8f2-a270cd38aaeb.png)

**Comment by mulle-nat** [comment]
Wrong project really. This is an issue for the equally unmaintained https://github.com/memononen/nanosvg

**Comment by ColleagueRiley** [comment]
oops :eyes:
