### ISSUE TITLE
Draw an Arc with a Hole

### ISSUE THREAD

**Issue by DCubix** [memononen/nanovg#651]
I'm trying to draw an Arc using NanoVG in C++ but I get the following artifact:
![image](https://user-images.githubusercontent.com/5081992/210845213-4a04ef62-3c2c-4a50-9e92-af83dac37876.png)

That triangle in the middle...
The desired result would be this:
![image](https://user-images.githubusercontent.com/5081992/210845451-241a9ac7-39e5-479f-9340-0f1aff8720aa.png)

This is my code:
```cpp
Rect b = bounds;
float radius = std::min(b.width, b.height) / 2;

const float thickness = 16.0f;
const float rotation = PI / 2;
const float gap = PI / 4.5f;

const float angleFrom = rotation - gap;
const float angleSpan = (PI * 2.0f) - (gap * 2.0f);

nvgBeginPath(ctx);
nvgArc(ctx, b.width / 2, b.height / 2, radius, angleFrom + gap * 2, angleFrom, NVG_CW);
nvgLineTo(ctx, b.width / 2, b.height / 2);

nvgPathWinding(ctx, NVG_HOLE);
nvgCircle(ctx, b.width / 2, b.height / 2, radius - thickness);

nvgFillColor(ctx, nvgRGBAf(0.0f, 0.0f, 0.0f, 0.6f));
nvgFill(ctx);
```

**Comment by memononen** [comment]
The `nvgPathWinding()` has weird API, it is not a state, but instead it sets the winding of the last path, so it should come after the `nvgCircle()`.

The composite path support is somewhat limited and you may have some rendering artifacts.

I recommend to draw the shapes as two arcs, one outside and one inside, if you can.

Something along these lines (untested):
```C
nvgBeginPath(ctx);
nvgArc(ctx, b.width / 2, b.height / 2, radius, angleFrom + gap * 2, angleFrom, NVG_CW); // outer
nvgArc(ctx, b.width / 2, b.height / 2, radius - thickness, angleFrom + gap * 2, angleFrom, NVG_CCW); // inner
```

**Comment by DCubix** [comment]
@memononen I tested it and I just needed to flip the start and end angles on the second line like this:
```cpp
nvgBeginPath(ctx);
nvgArc(ctx, b.width / 2, b.height / 2, radius, angleFrom + gap * 2, angleFrom, NVG_CW);
nvgArc(ctx, b.width / 2, b.height / 2, radius - thickness, angleFrom, angleFrom + gap * 2, NVG_CCW);
```

And it worked :D
![ModularSynth_XIHZkjT8eZ](https://user-images.githubusercontent.com/5081992/210924016-71dd4062-9f7d-4bdf-8687-affd3c675768.gif)
